### PR TITLE
add Dec and Jan workshops

### PR DESCRIPTION
**Pull request by raynamharris**
## PR Checklist

- [x] Release label added
- [x] PR category label added
- [x] PR mergeable
- [x] Clean build logs
- [x] Linked related issues
- [ ] Colorblindness test https://www.toptal.com/designers/colorfilter/

## PR Description

Adds links to wiki pages for the UNIX and AWS workshops taught in Dec 2021 and Jan 2022

## Preview link

https://cfde-training-and-engagement--504.com.readthedocs.build/en/504/

## Review format

Comments welcome

### CODE REVIEW

**Comment by jeremywalter** [comment]
December 15 link seems to be empty? https://github.com/nih-cfde/training-and-engagement/wiki/A-Hands-On-Introduction-to-AWS:-December-15,-2021%22

**Comment by raynamharris** [comment]
Ah, I was missing an opening quote. Should work now.

**Comment by jeremywalter** [comment]
A couple questions before I sign off on these: 
1) There are some widgets or something that aren't rendering in the preview (the show ups as :::success and :::failure and there is even a [TOC]. -- Do we care about these enough to 'fix' them if they need to be fixed? Especially considering that these are 'supplementary' materials we are providing for attendees?
2) The survey links are still in there... should we remove them and make that part of the SOP? I don't think it would ever be a big problem, but might be good practice anyway.

**Comment by raynamharris** [comment]
Excellent points @jeremywalter. 

You are correct. The :::success, :::failure, and [TOC] things do not render in GitHub as these are features of HackMD. When I started adding workshops, I saw that other workshops had left all the formatting, including links to surveys, as is, so I have deleted that. 

If you look at PR https://github.com/nih-cfde/training-and-engagement/pull/499, you will see similar record of the UNIX and AWS workshops where all the :::success, :::failure, and [TOC] formatting is intact so that when you start a new hackmd from the template, you get at the formatting. There, however, I have taken most of the survey links out so they have to be added for each new workshop.

**Review by ctb — APPROVED** [review]
trust the @raynamharris what could go wrong he asked

**Comment by raynamharris** [comment]
ah merge conflicts sigh

**Pull request merged**
