### PR TITLE
MIME type tutorial in CF specific tab

### PR DESCRIPTION
**Pull request by s-canchi**
This PR would:

- Add [DCC tutorial tab along with overview page](https://cfde-training-and-engagement.readthedocs-hosted.com/en/scanchi/DCC-Tutorials/)

- Add [MIME type tutorial](https://cfde-training-and-engagement.readthedocs-hosted.com/en/scanchi/DCC-Tutorials/MIME_types/) under the DCC tab with tabbed boxes syntax

Request review for code check along with general feedback about content. Review suggestions in PR comments or in notes. This issues was assigned high priority and thus request short turn around time (~1 week)

### CODE REVIEW

**Comment by marisalim** [comment]
@s-canchi here are my comments! https://hackmd.io/dqFrvoJXQFSJpLet7IZShg?edit
in the hackmd doc, the questions are topics that could use some more explanation, either in the text or as admonition tips/notes/warnings

**Comment by s-canchi** [comment]
Thank you @marisalim for the feedback. I have incorporated many of your suggestions in the [updated version](https://cfde-training-and-engagement.readthedocs-hosted.com/en/scanchi/DCC-Tutorials/MIME_types/).

**Review by jeremywalter — APPROVED** [review]
I created a PR with some grammar checks. The tutorial itself is a bit technical for me, but from a communication standpoint it checks out. I did not attempt to actually run the tutorial.

**Review by marisalim — CHANGES_REQUESTED** [review]
@s-canchi I did a full run through of all the tutorial code with the KF data in AWS. There are a few more steps that need to be added, and I had a few problems with the code (e.g., needed `sudo` for all the `roy` commands, the revert didn't revert). I only downloaded 5 of the KF files, as the tutorial only uses the `idat` file, so I recommend shortening the file list.

Please check my other comments in the [hackmd doc](https://hackmd.io/dqFrvoJXQFSJpLet7IZShg#81820-comments)!

**Comment by s-canchi** [comment]
@marisalim - Checkout the [updated tutorial ](https://cfde-training-and-engagement--138.com.readthedocs.build/en/138/CF-Tutorials/) which addresses all of your review comments. Improvements in this version include:
- Integration of website wide asciinema player for utility wise screencasts
- Multi page tutorial setup with landing page
- Newly added example files that can be downloaded in two quick commands
- Additional clarification for code and background

The two things missing in this version that will be corrected prior to release :
- Linking to AWS setup
- Linking to the KF registration only page (it is linked to the older version currently)

Please indicate if the new changes are approved for merge to `latest` after review.

**Review by marisalim — APPROVED** [review]

**Pull request merged**
