### PR TITLE
Update history.md

### PR DESCRIPTION
**Pull request by raynamharris**
## PR Checklist

- [x] Release label added
- [x] PR category label added
- [x] PR mergeable
- [x] Clean build logs
- [x] Linked related issues #532 

## PR Description

Adds April and May Introduction to R Workshops and the iHMP workshop

**Preview link**

https://cfde-training-and-engagement--533.com.readthedocs.build/en/533/

## Review format
Please check typos and links

## Timeline
No rush :)

### CODE REVIEW

**Comment by raynamharris** [comment]
Looks good, link works :)

Screen Shot 2022-04-27 at 1 46 12 PM

**Comment by raynamharris** [comment]
ready for review

Screen Shot 2022-05-12 at 3 00 06 PM

**Comment by jeremywalter** [comment]
March 23rd link is 404

**Comment by raynamharris** [comment]
thanks @jeremywalter fixed the link

**Review by jeremywalter — APPROVED** [review]

**Pull request merged**
