### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by s-canchi**
## PR Checklist

- [ ] Release label added
- [x] PR category label added
- [x] PR mergeable
- [x] Clean build logs
- [ ] Linked related issues
- [ ] Colorblindness test https://www.toptal.com/designers/colorfilter/

## PR Description
Briefly describe the changes this PR will add/address
**Preview link**
Add the RTD auto generated preview link

## Review format
Add how you would like to receive the review (direct editing, as comments, notes etc)

## Timeline
Add expected timeline to finish review and merge adding note for time critical updates

### CODE REVIEW

**Comment by marisalim** [comment]
can add links to the wiki and discussion board

**Review by abhijna — DISMISSED** [review]
lgtm

**Comment by abhijna** [comment]
Actually, I don't love having the workshops listed on this page. We will have to edit two files every quarter this way 😕 

I also added the contributions thing to the readme. lmk what you think @s-canchi @marisalim

**Review by marisalim — APPROVED** [review]
lgtm!

**Comment by marisalim** [comment]
oh oops, the AWS wiki page for next week's workshop is posted, that can be added to the readme now

**Pull request merged**
