### PR TITLE
Minor adjustments to the snakemake lesson

### PR DESCRIPTION
**Pull request by ctb**
## please do not merge yet

- [ ] discuss: do we want to link to the conda lesson in the install section?
- [ ] discuss: should we link to "Streamlining data intensive biology with workflow systems" anywhere? [ref](https://academic.oup.com/gigascience/article/10/1/giaa140/6092773?login=true)
- [ ] in the install section, do we want to provide wget instructions for Snakefile and environment.yml?
- [ ] I don't really know what "for single line commands" means [here](https://training.nih-cfde.org/en/latest/Bioinformatics-Skills/Snakemake/snakemake_2/), step 2
- [ ] discuss: in [this section](https://training.nih-cfde.org/en/latest/Bioinformatics-Skills/Snakemake/snakemake_3/) do we want to provide the `rm` command to clean up the directory?
- [x] titus: check that it's `.sa` and not `.sai` in snakemake_4.md
- [ ] update the conda steps in Setup: https://training.nih-cfde.org/en/latest/Bioinformatics-Skills/Snakemake/snakemake_1/

## PR Checklist

- [ ] Release label added
- [ ] PR category label added
- [ ] PR mergeable
- [ ] Clean build logs
- [ ] Linked related issues
- [ ] Colorblindness test https://www.toptal.com/designers/colorfilter/

## PR Description
Briefly describe the changes this PR will add/address
**Preview link**
Add the RTD auto generated preview link

## Review format
Add how you would like to receive the review (direct editing, as comments, notes etc)

## Timeline
Add expected timeline to finish review and merge adding note for time critical updates

### CODE REVIEW

**Comment by ctb** [comment]
note to self: add at least one and probably 2-3 exercises b/t steps 6 and 10 of https://training.nih-cfde.org/en/latest/Bioinformatics-Skills/Snakemake/snakemake_4/. examples solicited from other lessons!

**Comment by ctb** [comment]
also: add note about rule all and delete all output in https://training.nih-cfde.org/en/latest/Bioinformatics-Skills/Snakemake/snakemake_5/

**Comment by s-canchi** [comment]
Example exercise from conda: 
- First, install the blast software with version 2.9.0 using conda.
- second, try this example BLAST analysis in the conda environment. (we list all the commands along with whaat they are doing)
note: we also provide a hint to solving the first point. 

Exercise from AWS:
Launch a t2.nano, Ubuntu 20.04 LTS - Focal instance in the the East US (Ohio) region. Change the root storage volume to 16 GiB and add an additional EBS volume (8 GiB).
 Comment
Bonus points: Your added volume will persist after you have terminated your instance. Where can you find it?

**Comment by marisalim** [comment]
note - if you'd like to edit the lesson binder, edit on a branch [here](https://github.com/nih-cfde/training-snakemake-binder/tree/master)

**Comment by s-canchi** [comment]
It turns out by defining the conda environment using the `environment.yml` file, we have redefined the`base` env in the binder. So we don't need to create an additional `snaketest` env. The steps have been clarified in the [workshop notes ](https://hackmd.io/f6OHvQXjQC-hhgo4OhCZ1A?view#The-Setup).

**Comment by ctb** [comment]
Ready for some review, I think.

**Review by marisalim — APPROVED** [review]
Lgtm!

**Review by abhijna — APPROVED** [review]
Went through the changed files and they look ok :)

**Pull request merged**
