### PR TITLE
new tutorial on GH two-factor auth, PAT key generation

### LINKED ISSUE #294: Make a Github auth token tutorial
add as an internal CFDE tutorial --

```
Basic authentication using a password to Git is deprecated and will soon no longer work. Visit https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/
```

- https://git-scm.com/docs/git-credential-store
- https://docs.github.com/en/free-pro-team@latest/github/using-git/updating-credentials-from-the-macos-keychain
- https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/
- https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication --> not listed, but Duo app works too
- https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token

### PR DESCRIPTION
**Pull request by marisalim**
## PR Checklist

- [x] Release label added
- [x] PR category label added
- [x] PR mergeable
- [x] Clean build logs
- [x] Linked related issues
- [ ] Colorblindness test https://www.toptal.com/designers/colorfilter/ -n/a

## PR Description

Github is going to eventually require token instead of password to work on Github remotely. this tutorial shows how to set that up + two-factor auth.

These steps worked on my Mac, i'm not sure if it's different for Windows - especially for step 7.

also added text highlights for buttons/things you click

**Preview link**
https://cfde-training-and-engagement--301.com.readthedocs.build/en/301/CFDE-Internal-Training/github_auth_setup/

## Review format
- comments or direct edits

## Timeline
Feb

### CODE REVIEW

**Comment by s-canchi** [comment]
The PAT tutorial should specify selecting the scope when we first setup. When we first set it up I had not selected the workflow option. But trying to push changes to a workflow file in the published documentation repo gave this error:
```
To https://github.com/nih-cfde/published-documentation.git
 ! [remote rejected] scanchi-rename-fixes -> scanchi-rename-fixes (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/update_specs_preview.yml` without `workflow` scope)
```

When I tried to reset with git credentials I got this error:
```
remote: Permission to nih-cfde/published-documentation.git denied to s-canchi.
fatal: unable to access 'https://github.com/nih-cfde/published-documentation.git/': The requested URL returned error: 403
```

I had to create a new token with the updated scope, delete the git credentials, and delete the GitHub credentials in keychain access, before I was able to connect to the repo and push my changes. 

I will add these notes to this tutorial to clarify when I review!

**Comment by s-canchi** [comment]
Added update to scopes text along with some minor txt and click boxes formatting. The tutorial looks good to me!

**Review by s-canchi — COMMENTED** [review]
Added update to scopes text along with some minor txt and click boxes formatting. The tutorial looks good to me!

**Review by s-canchi — COMMENTED** [review]
lgtm!

**Review by s-canchi — APPROVED** [review]

**Comment by marisalim** [comment]
thanks @s-canchi! 

@josesanchez1815 - if you could check that these steps work on Windows, that would be great! Saranya added info about git credential manager core that will work across platforms and she says it should be easier than using the Windows native git credential manager

**Comment by abhijna** [comment]
Nice tutorial Marisa!
Here are some minor comments:
> Step 1: Go to Github account settings
Click on Settings from the top-right dropdown menu on your Github profile picture.
Click on Account security to go to the security page.

In this step, the page is not called "security". I think it's called "Passwords and Access"

Can you make it clear that step 5 and step 6 are not related to each other? You need to go back to the settings page after step 5 to do the things in step 6 and that was not immediately clear to me. 

In "Step 6: Generate a PAT" 
Can you explain what kind of thing I can input in the "Note" bar. Is it a random word or something I should try to remember for the future, or something else

> The token will look like a string of letters and numbers. Keep this page open - we will need to use the PAT key instead of our password to login at the command line.

Your image doesn't actually show the auth token. I know why, but maybe it would be helpful to say that in the text? 

> This warning: "Be sure to save the token somewhere safe (e.g., password manager). After you leave this page, the token will no longer be viewable."

Maybe this warning should come earlier, just so people don't close it on accident.

**Review by abhijna — APPROVED** [review]

**Comment by marisalim** [comment]
thanks @abhijna - made the edits!

**Comment by marisalim** [comment]
I tested the steps on Windows and they worked, so merging this in!

**Pull request merged**
