### PR TITLE
June 2021 Release

### PR DESCRIPTION
**Pull request by s-canchi**
## PR Checklist

- [ ] Release label added
- [ ] PR category label added
- [ ] PR mergeable
- [ ] Clean build logs
- [ ] Linked related issues
- [ ] Colorblindness test https://www.toptal.com/designers/colorfilter/

## PR Description
June 2021 website release!!

**Preview link**
https://cfde-training-and-engagement--458.com.readthedocs.build/en/458/

## Review format
Hopefully none

## Timeline
Before June 30th

### CODE REVIEW

**Review by abhijna — APPROVED** [review]
yayy!

**Review by marisalim — APPROVED** [review]
🎉

**Comment by jeremywalter** [comment]
I like the re-org! All the things click and go places and seem happy.

**Review by jeremywalter — APPROVED** [review]

**Comment by abhijna** [comment]
ok nevermind saranya, i did it! :)

**Pull request merged**
