### PR TITLE
Tutorials added

### PR DESCRIPTION
**Pull request by abhijna**
Jekyll, Sphinx installation and protected branches tutorials added to a new folder called Tutorials

### CODE REVIEW

**Comment by ctb** [comment]
I'll let you push the magic merge button @abhijna :)

**Comment by ACharbonneau** [comment]
Forgive me for being over-pedantic here...but it seems that no one checked to see that the 'how to render in a website' tutorial actually renders in the website😬

**Comment by ctb** [comment]
oh, this is one of the github.io sites?

**Comment by ACharbonneau** [comment]
its an RTD

**Comment by ctb** [comment]
On Thu, May 28, 2020 at 10:09:58AM -0700, Amanda Charbonneau wrote:
> its an RTD

https://cfde-training.readthedocs.io/en/latest/toc.html

**Comment by ACharbonneau** [comment]
I have recommonmark installed, so it should render ok once the files are in the toc. But, because I am teaching myself html like an animal, the layout does not automagically get the left hand menu from the TOC...because I haven't figured out how to do it...so it would have to get added to that template manually 😬

**Pull request merged**
