### PR TITLE
Josesanchez aws blast

### PR DESCRIPTION
**Pull request by josesanchez1815**
Intro to AWS - Vidlet + Script
BLAST Tutorial - VIdlet + Script
Images for Intro to AWS Script

preview site: https://cfde-training-and-engagement.readthedocs-hosted.com/en/josesanchez-aws-blast/

### CODE REVIEW

**Comment by marisalim** [comment]
@josesanchez1815 some website/render things to edit and then i'll look at content!

- take out spaces in .md file names
- add the new tutorial .md files to the .pages and index.md files
- the `#` are supposed to create a TOC for the md doc on the right side of the website page, but they're not rendering for the Intro to AWS and from the `Install BLAST software using Command Line` section onwards for the Blast tutorial

**Comment by marisalim** [comment]
@josesanchez1815 looks like you added image files to the images/, but the image paths in the md docs need to point to them; they're imgur paths at the moment

**Comment by josesanchez1815** [comment]
Ok I will find a way to adjust them from imgur paths to png/jpg files

**Comment by marisalim** [comment]
check out @s-canchi's image formatting for the zoom feature! :)

**Comment by jeremywalter** [comment]
I ran through Intro to AWS and got my instance up, but then it goes off into mobaxterm territory without explaining that it's only for Windows... this needs to be clear in the video (it's at least mentioned in the script), and there should be some explanation for MaxOS users as to what that step is for and what they will use instead (cuz I don't know!).

**Comment by marisalim** [comment]
i think for the MacOS part, there should be some merging/linking/rearranging(?) with the tutorial that @abhijna wrote for AWS

**Comment by josesanchez1815** [comment]
I can add a slide in the video that will highlight the fact that MobaXterm is for Windows users. As for the Mac OS directions for connecting instances, maybe we can add a section from Abhijna's tutorials to the script.

**Comment by ACharbonneau** [comment]
I have a bit of magic code that can fix a lot of the mac/windows problems. Let me put it into a tutorial and make sure it renders and if it works I think it will help here.

**Comment by josesanchez1815** [comment]
Accidentally put two of the same pull request. Omitting this PR for another that is more up to date.

**Pull request closed without merging**
