### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by josesanchez1815**
## PR Checklist

- [ ] Release label added
- [ ] PR category label added
- [ ] PR mergeable
- [ ] Clean build logs
- [ ] Linked related issues
- [ ] Colorblindness test https://www.toptal.com/designers/colorfilter/

## PR Description
Briefly describe the changes this PR will add/address
Add template slides for intro sequences for vidlets
**Preview link**
Add the RTD auto generated preview link

## Review format
Check if you like the slides and if not I can find some others

## Timeline
Add expected timeline to finish review and merge adding note for time critical updates

### CODE REVIEW

**Comment by marisalim** [comment]
the slide looks nice to me! nice assortment of blues :)

**Comment by josesanchez1815** [comment]
@marisalim @jeremywalter 
Could I get some help with these? I just need these approved before we can use them.
I plan to put these in the CFDE Logo Template Folder in google drive titled [Template Powerpoint](https://drive.google.com/drive/u/0/folders/14dOaf7-G4k7rCw5mL2Q5jdRWXrO0Y5i-)

**Comment by jeremywalter** [comment]
I just made a copy of the powerpoint as a google slide with the logo on it...

**Review by jeremywalter — COMMENTED** [review]
Okay, so I added the 'google slide' version of the ppt template and added the CFDE logo, but I put it upper left... the guide says lower left, so I moved it down (I'm not picky about where, but I guess we should choose one). The ppt one has it upper left but I think the pptx update is upper left.

**Comment by josesanchez1815** [comment]
I think the lower left would be good for future tutorials. But I am not super picky either about whether it is left top or left bottom. Just as long as we have consistency.

**Review by jeremywalter — APPROVED** [review]
LGTM

**Review by marisalim — APPROVED** [review]
good to go! just remember to edit the ppt file with the logo position.

**Comment by josesanchez1815** [comment]
@jeremywalter @marisalim Do you guys like the faded Common Fund Data Ecosystem Logo?
https://docs.google.com/presentation/d/1udMo02V_F7-V0zf-Vr7yzzeNbCwCO-Dj/edit#slide=id.p1

**Comment by jeremywalter** [comment]
I would like it as a watermark for slides, but as an intro page for vidlet I prefer the real deal... discuss! :P

**Comment by marisalim** [comment]
agree with @jeremywalter! we can use the faded version if we need a watermark.

**Comment by josesanchez1815** [comment]
Sure! We can use the real deal for intro to vidlets.

**Pull request merged**
