### PR TITLE
Windows jekyll add

### PR DESCRIPTION
**Pull request by marisalim**
I've added more to the jekyll tutorial for Windows. It's particular to Windows 10, which has the option now for a linux environment via Windows Subsystem for Linux (WSL) and Ubuntu. @jeremywalter I didn't use VS Code, so maybe you want to add to/keep your section as another way of running jekyll on Windows machines, as the commands differ slightly.

### CODE REVIEW

**Comment by abhijna** [comment]
The training website has the tutorial for jekyll (which is what you want to edit, i think), but the training website itself is build using sphinx and read the docs. sorry, i only have the mac tutorial for Sphinx installation:
https://cfde-training.readthedocs.io/en/latest/Sphinx_Tutorial.html

**Comment by marisalim** [comment]
you mean checking my changes locally? this worked for me: 

## How to clone an unmerged pull request
1. `git clone` the repo you want
2. `cd` into the repo
3. `git checkout -t origin/[name of branch]` to see the unmerged changes for specified branch. Yay, now you can try the new code/look at new files locally.

**Comment by abhijna** [comment]
or what Marisa said. That's here: https://cfde-training.readthedocs.io/en/latest/ProtectedBranch_HowTo.html

**Comment by jeremywalter** [comment]
Thanks very much for the comments... but most of this was for working with branch protection. I've had issues with rendering the site. I've also seen lots of chatter about being able to preview these on branches, but I'm not sure how/if that works yet. So I'm not ignoring this PR, I just haven't successfully rendered the changes which is what I want to do to check them.

**Comment by abhijna** [comment]
So it sounds like you've installed Sphinx and gotten it to work. I'm assuming you cloned the training repo and then when you run `make html` it makes a new folder (called `build`) and makes your html files for you? Now you're wondering how to render the site locally?

**Comment by abhijna** [comment]
Ok, Jeremy says I should take care of this for now.

**Comment by abhijna** [comment]
Ok I checked it and everything looks ok....

**Pull request merged**
