### PR TITLE
AWS and Blast tutorial updates

### PR DESCRIPTION
**Pull request by marisalim**
I updated the format per style guide for the new AWS and Blast tutorials. I also added/edited the content, and ran through the steps.  I've put my version on a separate branch for now - let's see how it looks before merging to Jose's branch!

preview for AWS: https://cfde-training-and-engagement--234.com.readthedocs.build/en/234/General-Tutorials/Introduction_to_Amazon_Web_Services/introtoaws1/

preview for Blast: https://cfde-training-and-engagement--234.com.readthedocs.build/en/234/Bioinformatics-Tutorials/BLAST-Command-Line/BLAST1/

### CODE REVIEW

**Comment by marisalim** [comment]
@josesanchez1815 could you take a look at the changes I made to your AWS and Blast tutorials on this PR? Let me know if it's ok to merge to your branch!
if the changes look ok, then this also counts towards approving your original PR :)

**Comment by marisalim** [comment]
oops @josesanchez1815 that `ls -lht` was intentional :) it provides more information about the file than `ls -l` by making the file sizes human-readable and sorts by file generation time. I'll add in an explanation of these `ls` flags.

**Comment by josesanchez1815** [comment]
oops sorry about that!

**Comment by josesanchez1815** [comment]
I made some changes to the Estimated  times and added some hyperlinks.

**Pull request merged**
