### PR TITLE
GWAS tutorial edits for key access pair, data download and instance recovery

### PR DESCRIPTION
**Pull request by abhijna**
Here's the preview: https://cfde-training-and-engagement.readthedocs-hosted.com/en/preview/
Addressed all comments from here: https://github.com/nih-cfde/training-and-engagement/issues/125 #124 #126 

The biggest change is that I took out the "Download data" section and included it as a step in the "Access AWS" page to make it easier for users to switch between ubuntu and mac terminals.  I had to move things around quite a bit, so please double-check the index page and flow of information (from Making an AWS account to Installation).
.

### CODE REVIEW

**Review by s-canchi — APPROVED** [review]
lgtm! I made two minor edits to the new changes that related to syntax. The updated sections read well. The only aesthetic aspect that I would suggest for change is the table in the tutorial overview page for both the Bioinformatics tutorials which now has a bottom bar to slide across. I preferred the previous version which had all the text in one view.

**Comment by ACharbonneau** [comment]
minor things:

the link isn't rendering as a link:
> You have now successfully launched your AWS instance. You will need some information from this amazon webpage to access your AWS computer, so do not close the page yet. If you happen to close the webpage: https://us-east-2.console.aws.amazon.com/ec2/v2/home?region=us-east-2#Instances:sort=instanceId


Is this supposed to be nested bullets? Or is something missing?

> - Key pair for AWS:
> - If this this your first time using AWS or creating a key pair: Choose the 'Create a new key pair' option from the drop down menu. Under key pair name, type 'amazon' and click save. The default location for saving files on a Mac is the "Downloads" folder -- that's where your key pair can be found. Next time you launch an instance, you can reuse the key pair you just generated.
>-  If you you have a previously generated key pair, you can reuse it to launch an instance. For this tutorial, it may be helpful to rename the key pair amazon.pem.
> 
> - Then check the acknowledgement box and click "Launch Instance".
>

**Comment by abhijna** [comment]
Thanks! Fixed both problems :)

**Review by ACharbonneau — APPROVED** [review]
apparently i forgot to hit approve

**Pull request merged**
