### PR TITLE
General GWAS tutorial + Snakemake

### PR DESCRIPTION
**Pull request by abhijna**
[Abhijna's GWAS tutorial and Marisa's Snakemake tutorial can be previewed here](https://cfde-training-and-engagement.readthedocs-hosted.com/en/abhijna_gwas/Bioinformatics-Tutorials/GWAS-in-the-Cloud/)

This is a general GWAS tutorial based on dog coat color data. It is based on the ANGUS tutorial, but there are a few differences.

1) it's a tutorial for AWS and not Jetstream
3) I added a summary statistics steps that I may or may not be interpreting correctly
2) there's background info 

It would be great if one of you could walk through the tutorial from start to finish. I'd be happy to hang out on zoom while you do it so we can work out the problems together. Or you can write down all the problems and post them as comments here.

Other things that need to be checked: 
- [x] - do all the images make sense?
- [x] - do I need to add more explanation?
- [x] - general formatting
- [ ] - make sure there's nothing weird on my terminal window images

### CODE REVIEW

**Comment by abhijna** [comment]
Things get messed up if a different instance is selected. Add text about specifically using Ubuntu Server 20.04 LTS (HVM), SSD Volume Type

**Comment by marisalim** [comment]
Nice tutorial! I did a first pass to check that all the links work, and that I can install software and run commands to the final output. @abhijna here are my [notes](https://hackmd.io/oFc0DCd4ROKuzFBm8Yv_YA?edit)! I added some screenshots for some steps that you might want to add/explain a bit more.

I'll do a second pass next week to help with output file interpretation :)

**Comment by abhijna** [comment]
wow thanks for the detailed comments! :)

**Comment by josesanchez1815** [comment]
image
 
So this is the issue I run into after I try to install Rstudio Server. I'm sure I can find a solution on the R studio site.
I was wondering if you ran into this issue earlier?

**Comment by s-canchi** [comment]
@josesanchez1815 - This error is related to Rstudio and does not impact the actual installation and for the remaining analysis steps. What this error is stating is that after Rstudio was downloaded it tried to open the web interface version i.e. Rstudio server; however, since the permissions of the EC2 instance are not compatible, it produced an error that it could not open the server.

**Comment by s-canchi** [comment]
Nice tutorial. Here are some of my [notes](https://hackmd.io/J6QW5PMaQPqcIJCkxYVd3A?both) from going over the tutorial as well as some suggestions. This might be refined with time but for the immediate deadline purposes, it works great!

**Comment by abhijna** [comment]
Thanks for the detailed comments, Saranya. I tried doing it the RStudio way when I set it up, ran into a couple of roadblocks, lost patience, and quit. So, thanks for the detailed description on how to set that up. I will incorporate the RStudio server method in my KF-specific tutorial and leave this one as-is for the deadline. I'm working on all the other changes now.

**Comment by ACharbonneau** [comment]
I would like every lesson to have a standard front matter section similar to https://cfde-training-and-engagement.readthedocs-hosted.com/en/jeremyfixes/Kids-First/Setting-up-your-KF-Portal-Permissions/KF_1_PortalOverview/ 

I'm open to reimagining the content somewhat, but I want all our lessons to have the same signposts so users know what to expect. 

We should for sure add "Time to complete this lesson: 10-20 minutes" or whatever to the front matter I have already

**Comment by josesanchez1815** [comment]
image

Hello! Is this specific to Mac OSX? I'm doing these things on an AWS instance. Up to this point, I have not downloaded anything on the Local computer. Is this something to worry about? Will this affect future steps of the tutorial?

**Comment by abhijna** [comment]
Jose, the data you are working with lives in a website called cyverse. We're downloading onto local computer and then uploading it into Amazon. That's the only step where you need to work on a local terminal (not the Ubuntu).  The steps I have for download and upload are mac terminal-specific.

You can't do any analysis without the data, so it's an important step :)

**Comment by abhijna** [comment]
> I would like every lesson to have a standard front matter section similar to https://cfde-training-and-engagement.readthedocs-hosted.com/en/jeremyfixes/Kids-First/Setting-up-your-KF-Portal-Permissions/KF_1_PortalOverview/

Marisa and I added landing pages to both our two tutorials. Comments welcome :)

**Comment by s-canchi** [comment]
@marisalim - The Snakemake overview looks good. My only suggestion would be to shift the Part 3 video to the final lesson page i.e. Run Trough the Workflow page. It would fit better and when the links on the introduction page are clicked it would go straight to the video. As of now, clicking the link on Part 3 lands on video of Part 2 and having to scroll down the page. 

@abhijna - The GWAS in cloud overview looks good. Currently in the Prerequisites admonition, it states needing Mac Terminal. Do you plan to add notes for running the tutorial on Windows OS  as well ? My suggestion would be to also include other OS like: "We also assume basic knowledge of the command line interface; the user must be comfortable with finding and opening the terminal window in MacOS or accessing the terminal interface via a terminal emulator or the Linux subsystem in Windows OS"
If not, then a disclaimer like: "The current tutorial assumes access to a UNIX/ Linux system (MacOS, HPC etc)" similar to what Marisa has on the Snakemake overview would add clarity.

**Comment by josesanchez1815** [comment]
I was able to run all of the commands up to the Manhattan Plots - wasn't able to produce a .bmp file. I think that's something I have to troubleshoot as others have not had this issue.

As a windows user, it may be helpful to add in the filezilla application to transfer files downloaded locally and transferred to the AWS instance. I can help with that after I finish my vidlets.

I do appreciate the small text boxes throughout the tutorial that include notes or errors about the programs or terminal commands inputted.

When I am learning new applications like PLINK or VCF tools, the small summaries for each tool are super great!

Does R and Rstudio need to be downloaded in the home directory?

Is the GWAS directory created from the home directory?

**Comment by abhijna** [comment]
Yeah, it would be great if you can help me with the windows specific instructions at some point. Doesn't have to be right away.

GWAS directory: yes it should be in the home directory. So at the end of the tutorial, you will have 2 directories, GWAS and vcftools.
R download: You can download R and Rstudio from the vcftools directory, no need to cd out.

**Pull request merged**
