### PR TITLE
Edits to release plan: inclusion of release notes workflow and checklist explanation

### PR DESCRIPTION
**Pull request by s-canchi**
## PR Checklist

- [x] Release label added -n/a
- [x] PR category label added
- [x] PR mergeable
- [x] Clean build logs
- [x] Linked related issues -n/a
- [x] Colorblindness test https://www.toptal.com/designers/colorfilter/ - n/a

## PR Description
This PR includes fixes to the release plan incorporating some of the suggestions from the stand up meeting of 09/15 as well as reorganization of the release notes workflow. 

## Review format
comments

## Timeline
Expect merge by internal deadline (8th Oct) for October release

## Reviewer Checklist

- [ ] spelling and grammar
- [ ] successful run of all installation and code chunks
- [ ] sufficient explanation and details for the tutorial content
- [ ] code syntax and naming convention
- [ ] adherence of tutorial format to style guide
- [ ] functional links (inter and intra)
- [ ] accessible hyperlink text

### CODE REVIEW

**Comment by marisalim** [comment]
for new features, are the release note categories different for the `feature` vs. `enhancement` tags?

will need to change the link to the style guide to the repo instead of hackmd when the style guide branch is merged

**Comment by s-canchi** [comment]
There are currently no differences between tags `features` and `enhancements`. If we wanted to differentiate between them we would also update the Features sub heading in the release notes as they are all lumped together now. If it helps, we can just stick to one label. I will update the training guide link and will merge this PR following the style guide merge.

**Comment by marisalim** [comment]
yeah, let's stick to 'new', 'feature', and 'fixes' :)

**Review by jeremywalter — COMMENTED** [review]
LGTM - but the Reviewer Checklist looks like it's not a checklist now?

**Comment by s-canchi** [comment]
Yes!! Good catch @jeremywalter 
That is part of a new workflow I implemented which will automatically generate a comment with the reviewer's checklist after a PR is opened. The reviewer can copy it to make it a checklist or use it as reference to review the PR. The PR template is now streamlined as well. What do you think ?

**Comment by jeremywalter** [comment]
@s-canchi can the list be auto-generated as a checklist? I might just not understand the purpose, but I don't imagine copying it and changing to a checklist every time will be convenient

**Comment by s-canchi** [comment]
I have updated the reviewer checklist to be in checklist format. The list by the bot will appear in raw markdown format, but will render as a checklist if you copy, paste and submit a comment. So each reviewer can copy the list and tick boxes as the review progresses. 
The main purpose for segregating the checklist was to streamline the PR template. Each repo gets only one PR template and some of these checklists don't apply when we merge into branches apart from `dev`. The workflow would  allow the reviewers to copy the checklist multiple times. With the reviewers checklist in the PR template, one or both the reviewers would have to copy the list, edit to make it a checklist and add as a comment.

**Review by jeremywalter — APPROVED** [review]
made several changes and edits, mostly formatting and some minor text reorganization... content looks good

**Pull request merged**
