### PR TITLE
Intro to Terra + lesson in devo banner

### LINKED ISSUE #412: lesson in development banners
for landing pages use `>` quotes; for lesson landing pgs + lesson pgs use css banner syntax:
```
div class="banner"><span class="banner-text">Lesson in Development</span></div>
```
lessons that need banner:

- [x] intro to terra
- [x] intro to gcp
- [x] gwas in cloud
- [x] rnaseq in cloud
- [x] sim seq reads
- [x] make a note of the new syntax in style guide #286

### PR DESCRIPTION
**Pull request by marisalim**
## PR Checklist

- [x] Release label added
- [x] PR category label added
- [x] PR mergeable
- [x] Clean build logs
- [x] Linked related issues -n/a
- [ ] Colorblindness test https://www.toptal.com/designers/colorfilter/ 

## PR Description

an intro to Terra lesson, what is it, setting up accounts, running workflow, demo custom workflow

**Preview link**
https://cfde-training-and-engagement--358.com.readthedocs.build/en/358/Cloud-Platforms/Introduction-to-Terra/

## Review format
add to comments/PR review and I will incorporate

## Timeline
may release

### CODE REVIEW

**Comment by marisalim** [comment]
Hi @josesanchez1815 this is still a draft! Not ready for review yet :)

**Review by josesanchez1815 — COMMENTED** [review]
I had a chance to go through the GCP content, now I need to go through the Terra Content before I approve anything. Just wanted to provide an update.

**Comment by abhijna** [comment]
Some comments/suggestions (still in progress due to error)

### Tutorial resources
- could add some links for WDL lessons/tutorials

### Setting up terra account page:
- Could add a link to the google cloud console. It might be this one: https://cloud.google.com/?utm_source=google&utm_medium=cpc&utm_campaign=na-US-all-en-dr-bkws-all-all-trial-e-dr-1009892&utm_content=text-ad-none-any-DEV_c-CRE_491414383178-ADGP_Desk%20%7C%20BKWS%20-%20EXA%20%7C%20Txt%20~%20GCP%20~%20General_GCP-KWID_43700060017842282-kwd-353549070178&utm_term=KW_gcp%20console-ST_gcp%20console&gclid=EAIaIQobChMIlbH0xqP08AIV4R6tBh01kwCjEAAYAiAAEgKSk_D_BwE&gclsrc=aw.ds

- Step 4: Set up Terra billing project: 
When you click the `+ create ` button, there's a pop up window that asks you to choose your google account (even if i was previously signed in). Then it bring you to this pop-up window:




- [x] Also, my interface looks a little bit different from yours. There's the word "create" next to `+`



- [x] Creating a billing account takes so long! If you accidentally refreshed the page before the account gets created, it's going to cause a set-up error. How do you delete an account that throws an error?
   - I added a note about this - unfortunately it is both slow and no you cannot currently easily delete billing projects

### Navigating Terra workspaces
- Would be nice to have a link to terra workspaces here. Even if it's just the landing page where all workspaces are listed. 

- What else can you do with your workspace section:
"You can make a clone of an existing workshop and edit it. This feature is useful if you want to use a publicly available workspace that has analysis workflows or data you want to use for your own project."

- [x] Under the "clone" tab. Do you mean workspace (and not workshop)?

- In this section:
1) In the workspace search bar, type "quickstart"
2) Click on the three dots at the end of the row for "Terra-Data-Tables-Quickstart"
3) Click Clone

- [x] Between 1) and 2), add a bullet point about choosing the "featured" tab

### Running workflows in Terra

- We have the AWS GWAS lesson under the bioinformatics tab, so maybe we should have the Terra GWAS lesson there too? Or move the AWS GWAS lesson to the Cloud platforms tab. Thoughts?
- [x] Step 2: Import data to workspace: Open the workspace created previously
The hyperlink you have in this sentence could point to the workspace instead of the workspace lesson. You can also add a sentence to direct them to the lesson if they've forgotten how to do so! 

- Step 3: Set up data table¶
I'm getting an error message when i try to copy and paste in the text import tab



I tried uploading it as a tsv but got the same error! 
- [x] added a downloadable tsv to upload

So this is where I'm at.

**Comment by josesanchez1815** [comment]
I'm also stuck at where Abhijna's last comment. I think we just need to take out the duplicate coat color in the table

image

**Comment by marisalim** [comment]
Hm, it's a problem with the tabs not being copy/pasted properly from the website to Terra. I think the alternative is to make a downloadable tsv file that can be uploaded.

**Comment by abhijna** [comment]
I tried to make it a .tsv file and that failed too ¯\_(ツ)_/¯

**Comment by marisalim** [comment]
try the one i added

**Comment by abhijna** [comment]
The tsv works now! Yayy!

### Running workflows in terra
When I clicked on "Find a workflow", this page and then click on the broad methods repo
Screen Shot 2021-06-24 at 2 00 53 PM

It takes me to this page:
Screen Shot 2021-06-24 at 2 00 31 PM

Then I had to sign in again and accept terms and conditions:
Screen Shot 2021-06-24 at 2 04 57 PM

After I launch my analysis, it took a while for the status to show up as "queued". How long are jobs usually queued? Mine has been sitting there for 2 hours! Is there an estimate you can put on the tutorial? What does it depend on?

### Custom workflows page
Still working on this part.

This is a very well-written and extensive lesson. Nice work @marisalim  🤟🏾

**Comment by marisalim** [comment]
2 hours?! yikes, i'll look up how long my demo took and add, but i don't think it was ever that long. 
--> it took about 10 minutes to complete the workflow ... maybe Terra is doing some maintenance or something's slowing the queue time...

Terra doesn't send notifications unfortunately, so I'd check progress in the morning.

**Comment by abhijna** [comment]
it completed the workshop pretty quickly (~10 ish mins), but sat in the queue for 2 hours before running. Maybe "just" add text to say that can happen sometimes?

**Review by abhijna — APPROVED** [review]
Ok done reviewing. lgtm for this release

**Pull request merged**
