### PR TITLE
Update conda tutorial format

### LINKED ISSUE #193: update conda tutorial format
we made some changes to the overall tutorial section layout. editing conda tutorial to update format + demo the new style guidelines

### PR DESCRIPTION
**Pull request by marisalim**
## PR type

- [ ] New tutorial
- [ ] Fixes to tutorials only on latest
- [ ] Fixes to tutorials on stable and latest
- [ ] Feature enhancement
- [x] Tutorial formatting
- [ ] Website formatting
- [ ] Other

## PR Checklist

- [x] Release label added
- [x] PR category label added
- [x] PR mergeable
- [x] Clean build logs
- [x] Linked related issues

## PR Description
we made some changes to the overall tutorial section layout. editing conda tutorial to update format + demo the new style guidelines

preview: https://cfde-training-and-engagement--199.com.readthedocs.build/en/199/General-Tutorials/install_conda_tutorial/

## Review format
i think this follows the style guide ;) let me know if you find format mistakes, edit directly or comment

## Timeline
before Oct 2020 release

### CODE REVIEW

**Comment by s-canchi** [comment]
I am not sure I like the overall format compared to the previous version. These are my main concerns:
- The opening bit with the table and admonition boxes looks busy. 
- I don't understand why the Miniconda explanation is in quotes. Is that our stance i.e. CFDE's opinion abut Conda ?
- I like the Step wise distinction but don't like the organization within a given Step with letters and bullet points. It is starting to look like a formal document (paper or thesis) :(
- Key point admonition under conclusion seems redundant. Either having the Conclusion or just the key point would work.

**Comment by marisalim** [comment]
re: the Miniconda quote, that's a direct statement from the website, so it's in quotes.

**Comment by marisalim** [comment]
@s-canchi @jeremywalter 

here's an alternative format version - let me know what you prefer: https://cfde-training-and-engagement--201.com.readthedocs.build/en/201/General-Tutorials/install_conda_tutorial/#step-2-verify-your-installer-hashes

**Review by jeremywalter — COMMENTED** [review]
I rather like the newer version with the tabs (I think it makes it less cluttered looking and saves space). I would point out that a prerequisite is literally just a thing you need in order to be able to complete the tutorial. In this case it might be just Mac OSx (perhaps a version as well?). Some tutorials will have more robust prereqs, but it's okay if it's just an operating system IMO... and not verbose... maybe just bullet points?

I would also suggest that the 'key points' admonition could be optional. In this case just the line under conclusion might suffice. For bigger tutorials the key points might come into play.

I don't like the size of the est time box... but I like the functionality. I think it should be smaller and less intrusive.

**Comment by s-canchi** [comment]
I think this version with the tab boxes works much better. I like the overall flow using the Step demarcation and concluding with Key Points. I actually prefer the admonition box instead of a conclusion title. I do however think there are some redundancies that we could do away with:
- The title is explicit about setting up Conda on MacOS, yet it repeats in the prerequisites. Maybe modify the title to remove the MacOS part or remove prerequisite tabbed box. I would do the former since we could add instructions for Conda install on Linux and Windows later.
- The lesson title and the title in the table don't match. Only estimated time info is important from the table and maybe could be a tabbed box instead ?

**Comment by marisalim** [comment]
@s-canchi ok, i edited the title + box title. the table will have page titles for the multi-page tutorials, so the formatting is slightly more redundant on 1-pagers. 

@jeremywalter the box format is a Mkdocs rendering of Markdown tables thing. I don't know how to make it less weirdly spaced. Suggestions?

**Comment by marisalim** [comment]
i think having learning objs and prereqs for each tutorial is important. perhaps key points can be optional

**Comment by jeremywalter** [comment]
Looking at Carpentries (again) and for the est time grid they call that a schedule... then inside the actual cells there are time marks on one side, and descriptions (usually questions being answered in that sub-section) on the right. 

image

Thoughts?

**Comment by marisalim** [comment]
@jeremywalter yes, the Carpentries style was absolutely the inspiration here! (see [Snakemake landing pg](https://cfde-training-and-engagement--201.com.readthedocs.build/en/201/Bioinformatics-Tutorials/Snakemake/) and [GWAS landing pg](https://cfde-training-and-engagement--201.com.readthedocs.build/en/201/Bioinformatics-Tutorials/GWAS-in-the-cloud/)).

for this specific conda tutorial, the "Description" column seemed redundant - i wasn't sure what to put there that wasn't already stated as a learning objective. I really like this table format for the longer multi-page tutorials. maybe for 1-pagers, we could just state the "Est. Time" at the top as text and do away with the table...?

**Comment by s-canchi** [comment]
@marisalim - I like the title. Could even had just said Conda instead of Miniconda (makes for better index in google search).
@jeremywalter - We have the table with the exact type of setup as the carpentries for the multipage tutorials, where each page of the tutorial is linked with estimated time and the description in questions format. 

I am starting to think the table for single page tutorial may not be necessary and we can instead add the estimated time as a tabbed box alongside prerequisites and such. Or maybe we can have the table with times, topics and description  in the landing page of the header where are the tutorials are hosted. So here it would be the index page of the General Tutorials tab and just have the estimated time in the actual page of the tutorial either in a tabbed box or a admonition box. Thoughts ?

**Comment by marisalim** [comment]
would this be sufficient for 1-page tutorials? https://cfde-training-and-engagement--201.com.readthedocs.build/en/201/General-Tutorials/install_conda_tutorial/

**Comment by s-canchi** [comment]
I think it looks good. Maybe fiddle with the est. time as a tabbed box. Do you think it would make sense to revamp the index page of the tutorial landing page with the table format linking the individual tutorials ?

**Comment by marisalim** [comment]
@s-canchi do you mean for the General Tutorials landing page?

**Comment by marisalim** [comment]
@s-canchi hm, maybe. but, let's shelve that as an enhancement (for when we decide whether/how to reorg the tutorial tabs). i'll add it to the wish list issue.

here is the version with Est. Time as a tabbed box: https://cfde-training-and-engagement--201.com.readthedocs.build/en/201/General-Tutorials/install_conda_tutorial/

**Review by s-canchi — APPROVED** [review]
Everything looks great!

**Comment by jeremywalter** [comment]
Yes yes yes! I like this! One thing I didn't say when I typed out my template proposal: for the one pagers it makes sense to leave parts out... I think the most important aspect of the template is keeping things in order.

**Comment by marisalim** [comment]
great, thanks @s-canchi and @jeremywalter i'll make some edits to the template for optional sections

**Pull request merged**
