### PR TITLE
Fixes to home page aesthetics and update carousel content

### PR DESCRIPTION
**Pull request by s-canchi**
## PR Checklist

- [x] Release label added
- [x] PR category label added
- [x] PR mergeable
- [x] Clean build logs
- [ ] Linked related issues
- [ ] Colorblindness test https://www.toptal.com/designers/colorfilter/

## PR Description

This PR address some aesthetics issues with the home page. The boxes for the bottom content are now all even. Also fixed the nav render issue with the latest MkDocs-material update. 

**Preview link**
https://cfde-training-and-engagement--324.com.readthedocs.build/en/324/
## Review format
comments and/or direct edits.

## Timeline
Feb release

### CODE REVIEW

**Comment by marisalim** [comment]
maybe add link to https://www.nih-cfde.org/events/

**Comment by jeremywalter** [comment]
spellcheck in workshop box --> ~~calender~~ --> calendar
I'm also advocating for the use of "hands-on" vs ~~hands on~~

**Review by jeremywalter — APPROVED** [review]
LGTM - bravo on the carousel fix

**Comment by abhijna** [comment]
Looks great!

**Review by abhijna — APPROVED** [review]

**Review by marisalim — APPROVED** [review]
🎉

**Pull request merged**
