### PR TITLE
Create first draft of updated TrainingPlan

### PR DESCRIPTION
**Pull request by jeremywalter**
This is first draft from [dib-lab/cfde/issues/50]. Re-name, edit, iterate as needed.

### CODE REVIEW

**Comment by jeremywalter** [comment]
> Well. There's certainly very little to argue with.

??

**Comment by ACharbonneau** [comment]
lol. The PR is empty :)

**Comment by jeremywalter** [comment]
> lol. The PR is empty :)
I think I fixed it?

**Comment by ACharbonneau** [comment]
That fixed it. Will look at it in the morning :)

**Pull request merged**
