### PR TITLE
Update home pg workshop box

### LINKED ISSUE #401: home page updates
- [ ] reminder to add the new workshops to home page from April/May

### PR DESCRIPTION
**Pull request by marisalim**
## PR Checklist

- [x] Release label added
- [x] PR category label added
- [x] PR mergeable
- [x] Clean build logs
- [x] Linked related issues
- [ ] Colorblindness test https://www.toptal.com/designers/colorfilter/

## PR Description

Add April and May workshops to home pg + workshop note links

**Preview link**
https://cfde-training-and-engagement--443.com.readthedocs.build/en/443/?next=https%3A%2F%2Fcfde-training-and-engagement--443.com.readthedocs.build%2Fen%2F443%2F&ticket=ST-1621888590-kX9dsD7GcuopwDdR4hPdF8xvjNx5UY1R

## Review format
direct

## Timeline
May

### CODE REVIEW

**Comment by abhijna** [comment]
Are we not adding pop-ups to this list of workshops?

**Comment by abhijna** [comment]
Otherwise lgtm

**Review by abhijna — APPROVED** [review]

**Comment by marisalim** [comment]
Oh we definitely can! I forgot them since I was looking at the wiki pg for note links

**Comment by abhijna** [comment]
Done! This is ready for merging 🙂

**Pull request merged**
