### PR TITLE
[WIP] Update snakemake lesson a bit, preparatory to day 2.

### PR DESCRIPTION
**Pull request by ctb**
- [x] discuss: do we want to link to the conda lesson in the install section?
- [x] discuss: should we link to "Streamlining data intensive biology with workflow systems" anywhere? [ref](https://academic.oup.com/gigascience/article/10/1/giaa140/6092773?login=true)
- [x] in the install section, do we want to provide wget instructions for Snakefile and environment.yml?
- [x] I don't really know what "for single line commands" means [here](https://training.nih-cfde.org/en/latest/Bioinformatics-Skills/Snakemake/snakemake_2/), step 2
- [ ] discuss: in [this section](https://training.nih-cfde.org/en/latest/Bioinformatics-Skills/Snakemake/snakemake_3/) do we want to provide the `rm` command to clean up the directory?
- [x] update the conda steps in Setup: https://training.nih-cfde.org/en/latest/Bioinformatics-Skills/Snakemake/snakemake_1/

## PR Checklist

- [ ] Release label added
- [ ] PR category label added
- [ ] PR mergeable
- [ ] Clean build logs
- [ ] Linked related issues
- [ ] Colorblindness test https://www.toptal.com/designers/colorfilter/

## PR Description
Briefly describe the changes this PR will add/address
**Preview link**
Add the RTD auto generated preview link

## Review format
Add how you would like to receive the review (direct editing, as comments, notes etc)

## Timeline
Add expected timeline to finish review and merge adding note for time critical updates

### CODE REVIEW

**Comment by ctb** [comment]
Ready for review & merge

**Comment by marisalim** [comment]
since we updated snakemake-minimal versions, i'm going to also add in the `-j` flag.

**Review by marisalim — APPROVED** [review]
lgtm!

**Comment by ctb** [comment]
(curious, is there a reason y'all don't merge the pull requests after approval?)

**Comment by marisalim** [comment]
(our habit has been to let the PR submitter have the final say/click merge 🙂 )

**Pull request merged**
