### PR TITLE
Training website style guide

### PR DESCRIPTION
**Pull request by marisalim**
**What:** The style guide for the website/tutorials is now several markdown pages in a [folder](https://github.com/nih-cfde/training-and-engagement/tree/marisa_style_guide/docs/TrainingRepoStyleGuide) in the `./docs` folder. There are [template markdown docs](https://github.com/nih-cfde/training-and-engagement/tree/marisa_style_guide/docs/TrainingRepoStyleGuide/tutorial_template_docs) for tutorial landing and main pages. 

These are sections that need more info or need a decision:
- [x] make `tutorial_scripts` folder to hold scripts? or should they stay with associated tutorial? **--> DECISION: keep tutorial-specific scripts in tutorial folder. will revisit this option if there's a need for it.**
- [x] please add guidelines about [vidlets/screencasts](https://github.com/nih-cfde/training-and-engagement/blob/marisa_style_guide/docs/TrainingRepoStyleGuide/4RecordingStyleGuide.md)!! e.g., when to use vidlet vs. screencast? where are they stored?
- [x] is the [practice repo section](https://github.com/nih-cfde/training-and-engagement/blob/marisa_style_guide/docs/TrainingRepoStyleGuide/6PracticeGithubRepos.md) about the [repo](https://github.com/nih-cfde/play-with-github) for practicing git? it needs more description about when/where it's used.
- [x] accessiblity: supposed to see text if mouse hovers over image (if `[there is text here](img/path)`), but it just shows the zoom magnifying lens... can screen readers still read the image? is there a different way to do this? **--> this can be a later thing as we learn how to test, just want to bring it to our attention**
- [x] add link to training release plan once it exists
- [x] revise [Review and Merge section](https://github.com/nih-cfde/training-and-engagement/blob/marisa_style_guide/docs/TrainingRepoStyleGuide/7ReviewAndMerge.md) pending release plan **--> now summary w link to release plan**

**Where:** The guide lives on the Github repo, and is not rendered on the website at the moment.

**How:** Let me know if you have suggestions and/or go ahead and edit directly, especially for to do list above! 

**When:** I'd like to finalize the guide ASAP so we have something to use for all the tutorials going forward! It's ok if we need to leave a few things as placeholders, just let me know which things!

### CODE REVIEW

**Comment by s-canchi** [comment]
I made a few changes:
- Added information about the asciinema player in feature list
- Added some definitions and context for vidlets and screencasts section
- Added context for the practice repo section

I will check to see if the mouse hover can be modified to display image but since that may take time, that will be a feature update for future. I don't have any strong opinions about `tutorial_scripts` but if it can made part of the `Resources` tab a centralized folder might make sense. Currently, the structure can remain as is with scripts in the associated tutorial directory. Similar restructuring can also apply for screencasts in the future if it becomes a common resource we include in our tutorials.

**Review by s-canchi — COMMENTED** [review]
I made a few changes:
- Added information about the asciinema player in feature list
- Added some definitions and context for vidlets and screencasts section
- Added context for the practice repo section

I will check to see if the mouse hover can be modified to display image but since that may take time, that will be a feature update for future. I don't have any strong opinions about `tutorial_scripts` but if it can made part of the `Resources` tab a centralized folder might make sense. Currently, the structure can remain as is with scripts in the associated tutorial directory. Similar restructuring can also apply for screencasts in the future if it becomes a common resource we include in our tutorials.

**Comment by josesanchez1815** [comment]
https://github.com/nih-cfde/training-and-engagement/pull/154

**Comment by jeremywalter** [comment]
The main and landing page templates are:

**Title -> Intro -> Setup -> Steps -> Conclusion
Title -> Description -> Learning Objectives -> Pre-Reqs -> Tutorial Resources -> (Steps?)**

I propose that we just use the landing page format for consistency, but I haven't written a tutorial so maybe my idea is terrible. What do y'all think? I think whether it's one page or multiple there should be an objective and some pre-reqs... set-up as well... something like

**Title -> Learning Objectives -> Pre-Reqs -> Setup -> Tutorial Resources -> Steps -> Conclusion**

**Comment by marisalim** [comment]
the content of the [Review and Merge](https://github.com/nih-cfde/training-and-engagement/blob/marisa_style_guide/docs/TrainingRepoStyleGuide/7ReviewAndMerge.md) page is basically repeating the release plan. I propose deleting this page from the style guide and referencing the release plan doc in the style guide instead. thoughts?

**Comment by ctb** [comment]
hot take: leave a quick summary of the process to merge into dev (create a PR,
etc.) then reference release plan doc after that.

**Comment by s-canchi** [comment]
I added in the explanation for Keys syntax which essentially adds in the keyboard keys for when we have commands. I also included the note about adding the video to the CFDE channel which helps manage permissions and keep all our videos in one place.

**Comment by marisalim** [comment]
I added the style guide to the website! It's in a new CFDE Internal Training tab, in its own Website Style Guide directory. Let me know if this needs more edits.

https://cfde-training-and-engagement--154.com.readthedocs.build/en/154/CFDE-Internal-Training/

**Comment by marisalim** [comment]
@s-canchi i have a link to the release plan [here](https://cfde-training-and-engagement--154.com.readthedocs.build/en/154/CFDE-Internal-Training/Website-Style-Guide/1WebsiteNavStyle/#website-host-and-github-branches). i'm not sure we want that on the website. thoughts?

**Comment by s-canchi** [comment]
The rendered version looks so nice! With regards to the release plan, I would suggest we **do not** make it public yet. In the future when we do have active external contributors, it would be useful to have the release documentation visible. But for now since it is work in progress, we can continue to use the hidden feature in navigation. The document would also need to reformatted prior to making it public.

**Comment by marisalim** [comment]
internal training tutorials have now been moved to CFDE Internal Training tab (git branches, cfde-bot, mime types, style guide) 🎉

**Comment by s-canchi** [comment]
Looking good. Couple of suggestions:

- [x] The Overview for CFDE Internal Training has tutorials in the title. That doesn't seem necessary. "CFDE Internal Training" is sufficient. The tutorials is also in lowercase.

- [x] The order of the tutorials in the overview list does not match the left side TOC. Can you ensure they match ?

**Comment by marisalim** [comment]
@s-canchi fixed :)

**Review by s-canchi — APPROVED** [review]
lgtm

**Pull request merged**
