### PR TITLE
Revamp of home page look and addition of carousel feature 

### LINKED ISSUE #240: Customize social media icons location
The social media icons and the links by default render in the footer of the website. It would be preferable if they appear next to the search bar on the top right corner.

### LINKED ISSUE #245: Update landing page with image slider
Integrate the landing page with a image slider which is clickable linked to the lessons as a way to offer the user the different tutorials that are available. The slider should be customizable and should work on multiple platforms and modes.

### LINKED ISSUE #254: Add Jira helpdesk link
We will be updating the help email link to Jira Helpdesk email. This is will either be via the Jira Widget or update the current help email on the training website.

### LINKED ISSUE #278: Corrections to CFDE logo
The current version of logo with the white outline looks skewed. The logo with the white outline however stand out against the  dark background. This version also does not have the CFDE spelled out. To keep consistency, require the logo with CFDE spelled out with white outline and scaled to correct dimensions. Also require a favicon of the logo without the CFDE spelled out (48x48 in RGB).
Preview link to current rendering: https://cfde-training-and-engagement--242.com.readthedocs.build/en/242/

@ACharbonneau

### PR DESCRIPTION
**Pull request by s-canchi**
## PR Checklist

- [x] Release label added
- [x] PR category label added
- [x] PR mergeable
- [x] Clean build logs
- [x] Linked related issues
- [x] Colorblindness test https://www.toptal.com/designers/colorfilter/

## PR Description
This PR includes a complete revamp of the home page of the training website. 
- The navigation on the home page is removed.
- A carousel slider is added which includes a snapshot of the tutorial images, short description, title and link to the appropriate tutorial pages. 
- The footer for home page is also customized to be on top of the page and for rest of the pages, it is rendered in a different color to distinguish from the nav links.
- Corrections to the color scheme for the side nav and titles in smaller media screen are also included
- Logo is now clickable and the title color is changed for non home pages.
- Testing completed in four different browsers and different screen sizes.
- Added helpdesk email.

**Preview link**
https://cfde-training-and-engagement--242.com.readthedocs.build/en/242/

## Requested Review/Feedback 

- [x] Need suggestions for the carousel images. Currently they are in 3 image format with background fill. Should we instead stick to one figure in a large format ? ---> **Reverted to single image format and included logos where possible**
- [x] Need suggestion on carousel title and content. Should we include all of them or parse it down? --> **We are including all of them for now.**
- [x] Do we need autoplay feature for the carousel ? --> I tested multiple versions of the autoplay slider but all had some problems (responsiveness, clickable links action, compatibility with template etc). Open to suggestions for some slider that can be integrated or for updating the stylesheet to include the autoplay feature. -> **Tested few more options, but each had some integration issues or feature issues. Dropping the autoplay capability feature till next release.**
- [x] Any other styling and font edits that should be included -> **Re-edited the home page to be similar in style and format to the portal website.** 

## Review format
Leave suggestions in the comments and I will edit them. 

## Timeline
Needs to be merged before 8th December.

### CODE REVIEW

**Comment by s-canchi** [comment]
The implementation needs improvement with the following:
- [x] make the images clickable to take the user to the relevant tutorial page
- [x] apply CFDE color scheme
- [x] reduce the size and relocate to make it less prominent
- [x] ensure it works across all browsers and modes
- [x] remove home page nav bar

This is scheduled for December 2020 Release.

**Comment by abhijna** [comment]
This is a very professional looking first page. My biggest concern is that it is very mismatched with the rest of the website. When you click on a tab it feels like we're going to another, unrelated website. Is there a way to keep the theme? Maybe make it black text on a white background but keep all the features?

> Do we need autoplay feature for the carousel ? --> I tested multiple versions of the autoplay slider but all had some problems (responsiveness, clickable links action, compatibility with template etc). Open to suggestions for some slider that can be integrated or for updating the stylesheet to include the autoplay feature.

Autoplay could be good as long as the delay is right.

**Comment by ACharbonneau** [comment]
This is neat! But I'm going to second Abhijna on the style being too jarringly different. In the overall CFDE-CC resources, we're trying to make the experience across websites as similar as possible. 

The homepage of the public website is: https://www.nih-cfde.org/
For the portal is: https://app.nih-cfde.org/

I originally made the theme we have to be similar to these. Can we keep the carousel, but make it more like the landing pages of these sites, that have an interactive element but the same general layout?

**Comment by s-canchi** [comment]
Both are good suggestions. I will undo the page wide color scheme to continue the same consistency. Let me attempt autoplay feature once again.

**Comment by jeremywalter** [comment]
Looking good! Is it possible/easy to enlarge the carousel box at all? The images are pretty tiny and there is still some space available in that section of the website.

**Comment by s-canchi** [comment]
It is relatively easy to make the carousel box bigger, but the relative sizes within the box will remain the same. So we might have more of the box portion but not necessarily larger image. Here is a screenshot of local render with larger box:
Screen Shot 2020-11-20 at 5 09 46 PM
I am not completely happy with the current images either but not sure how to improve appearance.

**Comment by ACharbonneau** [comment]
what is the carousel you are using?

**Comment by s-canchi** [comment]
I am using a generic CSS based carousel feature that I modified to be compatible with the home page template. The code for the carousel is available in the override css file.

**Comment by jeremywalter** [comment]
I'm poking around and wondering where the text is... I can't find where the training events is sourced (I'd like to tweak the text a little).

**Review by jeremywalter — APPROVED** [review]
You fixed what I was going to fix! I still want to add an oxford comma, but the words are good and everything seems to be working. What I'm curious about is the mechanism for future updates since it looks like some of the text is being added in HTML?

**Comment by s-canchi** [comment]
That's a valid point you bring up @jeremywalter ! I have been thinking about it too and wondering if we should have a separate document (maybe markdown or a separate HTML page?) that we can just source here. It will start to look very ugly as more content is added. I was thinking of implementing some alternate solutions for next time after some testing. But since the current format works for this release I didn't want to digress.

**Comment by marisalim** [comment]
minor edit - the "Past workshops" Blast link goes to the AWS tutorial

**Comment by ACharbonneau** [comment]
The overall format looks nice. 

- The "About" bit should say we're funded by NIH Common Fund, not NIH in general. 
- Management is spelled incorrectly in the carousel
- The KF blurb in the carousel seems to be missing some words, it doesn't quite make sense

**Comment by s-canchi** [comment]
- [x] The "About" bit should say we're funded by NIH Common Fund, not NIH in general. 
- [x] Management is spelled incorrectly in the carousel
- [x] The KF blurb in the carousel seems to be missing some words, it doesn't quite make sense

**Comment by marisalim** [comment]
edit requests!

- [x] for the Snakemake box -> "Learn how to create reproducible and scalable data analyses using the Snakemake Workflow management system".

- [x] for AWS -> should we spell it out in the header - "Amazon Web Services"?

- [x] for Analysis with Cavatica -> we don't have actual analysis in Cavatica tutorials yet. The tutorials are grouped under "Kids First Tutorials" right now. maybe something like this - "Learn how to transfer data subsets between the Kids First portal and Cavatica"

**Review by marisalim — APPROVED** [review]
Looks good!

**Comment by jeremywalter** [comment]
Just stopping by to look again... love the Past Workshop section (with links!)!

**Comment by abhijna** [comment]
LOVE it! 

Minor suggestions: 
- The intro blurb says "We’re working to make Common Fund data more accessible to researchers like you!". Maybe we shouldn't exclude clinicians?

- [x]  In the Past Workshops section the word "walkthrough" should be hyphenated

**Comment by s-canchi** [comment]
> The intro blurb says "We’re working to make Common Fund data more accessible to researchers like you!". Maybe we shouldn't exclude clinicians?

Considering our original goal was to target clinicians who are also involved in research, I would say researchers is a valid word that encompasses both the groups. Singling out clinicians also sounds very specific. We could maybe find a word that is more broader than researchers to use instead. Thoughts ?

**Comment by abhijna** [comment]
how about just "researchers and clinicians" instead of "researchers like you"

I don't super care either way. Just a thought.

**Review by abhijna — APPROVED** [review]

**Pull request merged**
