### PR TITLE
add sept oct nov workshops

### PR DESCRIPTION
**Pull request by raynamharris**
add Intro to Conda, Intro to R, and RNA-Seq in the Cloud workshops offered in September and October

## PR Checklist

- [x] Release label added
- [x] PR category label added
- [x] PR mergeable
- [x] Clean build logs
- [x] Linked related issues
- [x] Colorblindness test https://www.toptal.com/designers/colorfilter/

## PR Description
Briefly describe the changes this PR will add/address
**Preview link**
https://cfde-training-and-engagement--474.com.readthedocs.build/en/474/

## Review format
Add how you would like to receive the review (direct editing, as comments, notes etc)

## Timeline
Add expected timeline to finish review and merge adding note for time critical updates

### CODE REVIEW

**Comment by s-canchi** [comment]
I don't see the added workshops in the built website. Hm..

**Comment by raynamharris** [comment]
I added a few more workshops from November and fixed the October workshop links

**Comment by s-canchi** [comment]
I still don't see the workshops in the rendered website (link in the top comment). Do you ? Could you try making the changes locally and pushing it to see if that works ?

**Comment by raynamharris** [comment]
No, I did not make changes locally. I would prefer to not have this repository cloned on my local computer if possible.

**Comment by s-canchi** [comment]
I am not sure why but for some reason the changes you made on GitHub don't seem to show up on the rendered website. I can make a new branch with the same additions and push it to check it that fixes it. Thus far, except minor text edits, we usually end up making changes locally before pushing it to this repo. That is mostly because we can see a local version of the rendered site prior to pushing changes.

**Comment by raynamharris** [comment]
This is finally on the built website :) Good to go.

**Review by s-canchi — APPROVED** [review]
LGTM!

**Pull request merged**
