### PR TITLE
SCanchi edits to Protected Branch Tutorial

### PR DESCRIPTION
**Pull request by s-canchi**
Rendered site on preview looked good. Requesting review prior to merge on latest website live version. This commit includes modifications to text, fixing of broken GitHub links and additions of git commands to basic workflow section.

### CODE REVIEW

**Comment by marisalim** [comment]
see first answer: https://stackoverflow.com/questions/49185530/git-does-not-require-a-git-extension-when-cloning-from-github-is-this-a-featur

**Comment by s-canchi** [comment]
Would this matter for the practice repo though ? Since it is unlikely to be multiple people collaboration type repo. I understand now the significance of adding the .git extension but in the tutorial if it is to be presented adding a short description might be helpful.

**Comment by marisalim** [comment]
Hm, dunno. I `git clone` the repo addresses based on what's here: 
image

**Comment by s-canchi** [comment]
Preview [link](https://cfde-training-and-engagement.readthedocs-hosted.com/en/preview/General-Tutorials/)
Made changes to all tutorials to varying degrees including addition of new text and code, linking GitHub repo, fixing syntax issues and added admonition blocks. Request review to merge to master.

**Comment by jeremywalter** [comment]
LGTM - fixed a couple inline links (I don't know what those are called...), my changes (KF Tutorial) are in the preview but they are in a different part of the repo so after this is approved/merged I'll pull mine. Seems not as fraught with disaster as I had imagined yesterday.

**Comment by abhijna** [comment]
Here is my review:

### Protected branches tutorial comments:

1) Using a practice repo is a great idea. Make sure you indicate what parts of the code one would change for their own repo. For example: git clone https://github.com/nih-cfde/play-with-github.git
You could add a sentence: the example repo is called play-with-github. For your own repo, replace play-with-github with the name of your repo. 

2) You could add an admonition to this:
!!! Note
          It is critical to navigate to the directory in which you wish to make these changes.

3) You might want to add notes (from what Titus said today) to the `git add .` and git `commit -m` part part.

4) Preview website on GitHub branch part: make the admin privileges text an admonition. !!! Important

### Rendering a GitHub website locally with Jekyll

1) MacOS, WindowsOS, etc links at the top of the page are broken.

2) Same comment about making notes admonitions with !!! Note

3) Someone else needs to check the windows installation steps.

### Mkdocs tutorial

1) There's a typo on this line (you're missing a "with": These changes are reflected in the website with the Home, About icons on the left along Search, Previous and Next on the right side on the top navigation bar.

1) The readthedoc.com link seems to be broken.

**Comment by jeremywalter** [comment]
> ### Rendering a GitHub website locally with Jekyll
> 1. MacOS, WindowsOS, etc links at the top of the page are broken.

I think I fixed these in my commit, but perhaps the commit needs to be reviewed? It doesn't have a happy check mark. A new question for Titus teaches Github?


> 2. Same comment about making notes admonitions with !!! Note
> 3. Someone else needs to check the windows installation steps.

**Comment by marisalim** [comment]
@jeremywalter i think it's because your changes haven't been pushed to the preview branch

**Comment by abhijna** [comment]
Wait, why can't you push to preview now? Shouldn't you be able to pull the latest changes and push to both this branch and the preview branch?

**Comment by jeremywalter** [comment]
Excellent point @marisalim !! I never thought to push my commits on somebody else's branch to another branch. Kinda disorienting... and I didn't keep track of how I actually ended up figuring it out (I pushed lots of not dangerous buttons)... and now it's rendering with my fixes... so hurray... I learned something and can't teach anybody what I did... and hurray... the links are happy and lovely.

**Comment by marisalim** [comment]
😄 looks like you edited the docs on saranya's branch and then did a PR to push her branch to preview, so now the new changes can be built into the preview website!

**Comment by s-canchi** [comment]
I have made all the necessary changes and it renders without errors on the preview branch. If required, the branch is ready to merged to master pending confirmation of Windows installation steps.

**Comment by marisalim** [comment]
I'll check the windows wsl part today

**Comment by marisalim** [comment]
made some edits for the Windows WSL sections, edits rendered fine on the preview website. @s-canchi looks good to go!

**Pull request merged**
