### PR TITLE
Update snakemake tutorial format

### LINKED ISSUE #194: update snakemake tutorial format
we made some changes to the overall tutorial section layout. editing snakemake tutorial to update format + demo the new style guidelines

### PR DESCRIPTION
**Pull request by marisalim**
## PR type

- [ ] New tutorial
- [ ] Fixes to tutorials only on latest
- [ ] Fixes to tutorials on stable and latest
- [ ] Feature enhancement
- [x] Tutorial formatting
- [ ] Website formatting
- [ ] Other

## PR Checklist

- [x] Release label added
- [x] PR category label added
- [x] PR mergeable
- [x] Clean build logs
- [x] Linked related issues

## PR Description
we made some changes to the overall tutorial section layout. editing snakemake tutorial to update format + demo the new style guidelines

preview: https://cfde-training-and-engagement--197.com.readthedocs.build/en/197/Bioinformatics-Tutorials/Snakemake/

## Review format
i think this follows the style guide ;) let me know if you find format mistakes, edit directly or comment

## Timeline
before Oct 2020 release

### CODE REVIEW

**Comment by abhijna** [comment]
Looks good to me. Here are some very minor comments:

### snakemake overview
1) typo: "These materials **were was** adapted from the Data Intensive Biology lab course materials (course materials, lab materials)."

### Introduction + setup
2) I would take out the `.` after a command that people might copy and paste. For example on the setup page: 
If you get an error, the software installation may have failed. You can check the software that is installed in your conda environment`conda list`.
To leave the conda environment, type: `conda deactivate`.

### The Snakefile
3) I guess you should put quotes around Snakefile everywhere it appears..? This is a sentence from "The Snakefile" page:
```
Let's take a look at the Snakefile using the nano text editor:
```
I think it makes sense to **not** put it in quotes every time, but that would be violating the style guide :D 

4) Why is the word snakefile in single quotes in this sentence in the "Exercise" box of the snakefile page?
```
save the change by hitting control key and o key. nano will ask if you want to save the file as 'Snakefile'. We want to keep the same file name, so hit return key.
```
5) Is there a convention for when to use a simple code block vs. a code block with input/output type tabs? For example, the Snakemake rule box doesn't have output but it still has a "Snakemake rule" tab.

### Decorating the Snakefile
6) super nitpicking here: command/commands can be command(s)

**Review by abhijna — APPROVED** [review]

**Comment by marisalim** [comment]
@abhijna i shall write in an exception/clarification re: "I think it makes sense to not put it in quotes every time, but that would be violating the style guide :D" because i don't want to put quotes around it every time :P 

thanks! i will do the other edits, doing some more format fiddling over on the conda PR, so there will (probably) be a few more changes here.

**Comment by marisalim** [comment]
i'll add some more notes about code blocks into the style guide. 

i formatted snakemake rules as tabbed boxes called "Snakemake rule" instead of "Input" to distinguish between code that goes in the Snakefile vs. code that goes in the terminal.

**Comment by josesanchez1815** [comment]
### Grammar - 



- This needs a comma after visualization and a period after etc.

So, I noticed that the prequesities and Tutorial Resources are put into tabs.



### The style guide shows that admonition box is being used. 



### I think its ok to use the tab boxes. Its a nice change because you are using the admonitions quite a bit on that landing page.

The link to the pangeo binder `launch binder` jumps out at you :+1: 
Might be worth fixing. Its not a big deal.

**Comment by marisalim** [comment]
@josesanchez1815 yes! haha, i just changed prereqs and tutorial resources to use tabbed boxes instead of having so many admonition boxes.

the pangeo binder button - i think that's the zoom feature. i'm not sure how to tell zoom not to zoom on the button..

**Review by josesanchez1815 — APPROVED** [review]
See Latest Comment. But, aside from a few typos. Looks Good To Me.

**Pull request merged**
