### PR TITLE
Adding IDG tutorials

### PR DESCRIPTION
**Pull request by raynamharris**
## PR Checklist

- [x] Release label added
- [x] PR category label added
- [x] PR mergeable
- [x] Clean build logs
- [x] Linked related issues #484 
- [ ] Colorblindness test https://www.toptal.com/designers/colorfilter/

## PR Description

This PR adds a page with links to IDG resources. I used a docx - markdown converter to generate this text from the document in #484. Once I get a preview, I will make some formatting changes so it looks nice.

## Preview link 

https://cfde-training-and-engagement--505.com.readthedocs.build/en/505/

## Review format

Comments or edits are welcome.

## Timeline

Should be able to finish this today

### CODE REVIEW

**Comment by raynamharris** [comment]
Ready for a review. Any typos or major formatting issues? @nih-cfde/training

**Comment by jeremywalter** [comment]
I did some formatting (to make it more uniform). Also... not sure about two things:
1) 
image
One of these does not look like the other...
also
2) IDG is in the sidebar but not on the landing page overview here:
image

**Comment by raynamharris** [comment]
Thanks @jeremywalter! Unlike Kids First and the portal, this tutorial is contained in a single page (IDG.md) rather than a directory with lots of pages. I updated the index so that IDG is included on the landing page and not just in the TOC.

**Review by jeremywalter — APPROVED** [review]
LGTM - just rearranged the lessons to match sidebar

**Pull request merged**
