### PR TITLE
Javascript tutorial for adding content chooser and integration of content tabs and superfences

### PR DESCRIPTION
**Pull request by ACharbonneau**
This PR would:

- add support for [content tabs](https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/) and [superfences](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/) which together enable [end user changeable boxes that can display text and code](https://cfde-training-and-engagement.readthedocs-hosted.com/en/amanda/Bioinformatics-Tutorials/Snakemake_tutorial/snakemake_1/#4-test-that-your-environment-is-ready-to-go)

- add an example of [javascript based user-changeable content](https://cfde-training-and-engagement.readthedocs-hosted.com/en/amanda/General-Tutorials/Jekyll_Tutorial/)

- adds [a tutorial for adding a simple javascript content chooser to a website](https://cfde-training-and-engagement.readthedocs-hosted.com/en/amanda/General-Tutorials/javascript_chooser/)

### CODE REVIEW

**Comment by ACharbonneau** [comment]
As a process based aside, note that this merge is to *latest* not stable, so changes will not be pushed to the website until the next release to stable. So, if we *don't* want to keep some of my example changes that's fine, they can be reverted, but there's no concern that the rest of the surrounding tutorial needs to be updated to match, because that can be done as we move closer to release (by people who aren't me :) )

**Review by marisalim — APPROVED** [review]
Looks good! I'll approve because you can probably add the comments below as issues for all of us to work on + incorporate the javascript into the rest of the tutorial pages.

- javascript tutorial = 1) point out js key words that can't be used as variable names (e.g., 'option', 'select', 'script', 'div', 'function'), 2) add the complete tutorial script either at the end or in a separate page to show where all the js script ended up relative to the markdown text, 3) the right-side TOC isn't rendering
- snakemake pg = i love it! 
- sphinx pg = looks good!
- jekyll pg = the right-side TOC isn't rendering. I prefer the OS tabs you made on the sphinx page for this jekyll page, rather than the button. Some of the sections are a bit mixed with OS outputs, but this tutorial (as a separate PR) needs a lot of reorg/checking of sections because the different OS instructions are a) slightly different formats and b) sprinkled throughout in difficult to block off ways.
- KF advanced queries pg = looks good! the zoom feature doesn't quite work here - the tab text seems to be overlapping so you can't see the image. but if there's a way to fix it, it'd be nice instead of sending to a new page when you click the image.
image

**Comment by ACharbonneau** [comment]
> * javascript tutorial = 1) point out js key words that can't be used as variable names (e.g., 'option', 'select', 'script', 'div', 'function')
Sounds reasonable. Unfortunately putting `<div>` into the text gets read as a for real div no matter what I do, so I went with `div` (same for select, script, etc). Are you thinking just a list? 

2) add the complete tutorial script either at the end or in a separate page to show where all the js script ended up relative to the markdown text
I actually had this and then forget to add it to my commit. I'll re-add it

3) the right-side TOC isn't rendering
uh. I don't know why it's not. My guess is that when I went back through and removed all my `<div>` and similar from the prose I missed one and it's janking up the html :/

> * jekyll pg = the right-side TOC isn't rendering. I prefer the OS tabs you made on the sphinx page for this jekyll page, rather than the button. Some of the sections are a bit mixed with OS outputs, but this tutorial (as a separate PR) needs a lot of reorg/checking of sections because the different OS instructions are a) slightly different formats and b) sprinkled throughout in difficult to block off ways.

I'm fine with just reverting this one

> * KF advanced queries pg = looks good! the zoom feature doesn't quite work here - the tab text seems to be overlapping so you can't see the image. but if there's a way to fix it, it'd be nice instead of sending to a new page when you click the image.

This isn't what I see on that page...
image

image

I wonder if this is some kind of browser issue? I'm in chrome, what do you use? And/or is anyone else seeing that?

**Comment by marisalim** [comment]
Sorry, clarification on the image - the one i posted was me trying to use the zoom feature saranya added. But it has that overlap thing, so I changed it back to what you had :)

**Comment by marisalim** [comment]
yeah, for the javascript commands, a list and maybe as a tip/warning?

**Comment by ACharbonneau** [comment]
> Sorry, clarification on the image - the one i posted was me trying to use the zoom feature saranya added. But it has that overlap thing, so I changed it back to what you had :)

ooooh. I'll pull in that zoom and see if I can fix it

**Comment by marisalim** [comment]
does the demo javascript need the </script> on line 18?

**Pull request merged**
