### PR TITLE
Page nav buttons and tutorials

### PR DESCRIPTION
**Pull request by abhijna**
Here are some changes I made:
1) "next topic" and "prev topic" buttons to the bottom of each page #45 
2) added some hover highlighting: for fun.
3) added a title to the toc page: https://github.com/dib-lab/cfde/issues/79
4) added Jekyll, sphinx and protected branches tutorials to the website #53 

Please leave suggestions in comments here or make small changes yourself. Thanks!

### CODE REVIEW

**Comment by abhijna** [comment]
You will have to either clone and render locally or merge to see changes

**Comment by abhijna** [comment]
Here's a link to the changes: https://cfde-training.readthedocs.io/en/preview/

**Comment by ACharbonneau** [comment]
I think this looks good! my only comment/request is could we come up with a slightly better set of headings for the left side? something like DCC lessons and general lessons...except not those words, because no one in the world but us calls the DCCs DCCs :/

**Comment by abhijna** [comment]
Hmm... yeah I don't have any good titles either. I'm thinking something like "Program-specific lessons" and "general tutorials".  But those are long. Open to other suggestions. Should I post it as an issue or keep this PR open?

**Comment by ACharbonneau** [comment]
I think we can merge it and think of a title. maybe make a title discussion issue?

**Comment by abhijna** [comment]
something's wrong... it merged ok, but it's not rendering any of the changes. Hmm....

**Comment by ctb** [comment]
It may take some time for RTD to update. If it's not updated now, then there's a problem :)

From [this page](https://readthedocs.org/projects/cfde-training/builds/), looks like it might have updated now?

**Comment by abhijna** [comment]
It's working!

**Pull request merged**
