### PR TITLE
December 2020 Release

### PR DESCRIPTION
**Pull request by abhijna**
## PR Checklist

- [ ] Release label added
- [ ] PR category label added
- [ ] PR mergeable
- [ ] Clean build logs
- [ ] Linked related issues
- [ ] Colorblindness test https://www.toptal.com/designers/colorfilter/

## PR Description
Briefly describe the changes this PR will add/address
**Preview link**
https://cfde-training-and-engagement--295.com.readthedocs.build/en/295/

## Review format
Add how you would like to receive the review (direct editing, as comments, notes etc)

## Timeline
Add expected timeline to finish review and merge adding note for time critical updates

### CODE REVIEW

**Comment by abhijna** [comment]
This PR is ready for your approval

**Comment by jeremywalter** [comment]
Are we including the 'website features' stuff now? And side question... where are the old release notes archived? Cuz I can't see the previous set and I don't know where I'd look since they're not under 'Release Notes'. Is that by design? Otherwise... LGTM.

**Comment by s-canchi** [comment]
@jeremywalter - Yes we do have the option to include website features. Since the home page now looks completely different, it made its way to the release notes. Future fixes or streamline to the aesthetics will probably not. As far as the older release notes, we will only have the GH repo release notes. Did you want to archive the notes on the website too ?

**Comment by jeremywalter** [comment]
I don't have a strong opinion about what's in the notes as I'm mostly here to kick the tires, but I would say that the website section should be pushed to the bottom (users will be interested in the links to new tutorials and updated ones before what colors we've changed) and the matomo thing should just be left out... I've never seen a site brag about analytics (though I assume most have it integrated). ;) 

As for the archive... something we could integrate later if it's wanted. That was also more an observation and concern that maybe it was not intentional. As a ''use case'... sometimes when I come to a site I haven't visited in a few months, I might cruise through the release notes to see what I've missed... so I think it's potentially a good thing to have available.

**Comment by josesanchez1815** [comment]
Would it be possible to include information about updating the screenshots in our intro to aws tutorial?
Updates to Kids First Portal tutorials: Screenshots and text updated to match new versions seen on AWS Website

**Comment by josesanchez1815** [comment]
I think the archived release notes would be cool. We could see how we have developed this site over time.

**Comment by s-canchi** [comment]
Sorry Jose! I just saw your comment about the intro to was screenshots update after I merged the release notes PR. Were the screenshots updated in a separate PR ? I don't remember seeing it as a title. We can definitely add to the GH release notes interface but maybe late for the public documentation. 
Check out the latest website build. We now show all the release notes with latest being the front facing.

**Review by s-canchi — APPROVED** [review]
lgtm! Another successful release :)

**Comment by josesanchez1815** [comment]
The screen shots were updated on your carousel PR

**Review by josesanchez1815 — APPROVED** [review]
LGTM

**Review by marisalim — APPROVED** [review]
good to go!!

**Review by jeremywalter — APPROVED** [review]
LGREATtoMe!

**Comment by abhijna** [comment]
wooo!!! thanks y'all

**Pull request merged**
