### PR TITLE
October 2020 Release

### PR DESCRIPTION
**Pull request by s-canchi**
## PR Checklist

- [x] Release label added
~~- [ ] PR category label added -n/a~~
- [x] PR mergeable
- [x] Clean build logs
~~- [ ] Linked related issues - n/a~~
- [x] Colorblindness test https://www.toptal.com/designers/colorfilter/

## PR Description
This PR will merge all the latest updates from `dev` to the public facing website and is part of the October 2020 release. 

**Preview link**
https://cfde-training-and-engagement--246.com.readthedocs.build/en/246/

## Review format
Hopefully there are no changes, but if there are please create a PR to `dev` and merge to update the changes. 

## Timeline
On or before October 15, 2020

### CODE REVIEW

**Comment by ACharbonneau** [comment]
I hadn't really clicked through the whole portal tutorial until today, and it's got way more than I expected! That's awesome :) 

I do think we should change this line in the description tho:
> Researchers will learn how to apply for protected data access for files included in their manifest.

There is a place where you tell them that dbGaP has instructions, but we don't really teach people how to do it. I think I would just drop that line. 

Also, in the left panel, can we change the topics for this tutorial? the longer ones are really good, but I honestly had no idea what was going to happen when I clicked on "Blood Cancer" or "Movement Related Disorders". I think it would be fine to just get rid of those two headers completely and just have the more informative titles that are under them anyway. The extra navigation doesn't seem to be doing anything other than being slightly confusing. 

I also think it would be a lot nicer/friendlier if each of the top navigation pages for the website had a line or two of explanation. (Bioinformatics Skills, Cheat sheets, etc). Right now, the landing pages for those are just lists of links. But they should really have just a bit of text first. Something like what Jeremy proposed for 'short explanations of what each tab is' except it should be in the tab, rather than on the front page.

**Comment by s-canchi** [comment]
Those are some good comments. I will drop the line about the restricted data access. With regards to TOC structure I will wait to hear some team consensus since it was suggested by the reviewers of the PR @abhijna and @marisalim to implement the current structure. Will also add in the brief explanation to each tab.

**Comment by abhijna** [comment]
title suggestions:

Use case 1: Gathering and finding datasets related to blood cancer
Use case 2: Gathering and finding datasets related to movement disorders

or just

Use case 1: Gathering datasets related to blood cancer
Use case 2: Gathering datasets related to movement disorders

**Comment by josesanchez1815** [comment]
For the Web Development I think the estimated times to complete tutorials should be tables rather than tabs. Its nice to see all that information in a single format rather than clicking through all the tabs. That's one suggestion I have. It can wait til our next deadline if need be. Or I can make the changes. @s-canchi @abhijna @marisalim @jeremywalter

**Comment by s-canchi** [comment]
That's a valid point @josesanchez1815. However, unlike the multipage tutorials, the table format for the the single page will have redundant information for lesson name and description. Table format for only one column also seems excessive. Hence, the tabbed format was chosen to instead include all the associated information. If we change it to the table for tutorials under Web Development tab we would have to change the format for all other single page tutorials. I think we can revisit the format for the next release if need be.

**Review by ACharbonneau — APPROVED** [review]
I obviously didn't read all of the everything, but I trust you all did. And I think the overall website feel is delightful

**Review by marisalim — APPROVED** [review]

**Comment by ctb** [comment]
+1

**Review by abhijna — APPROVED** [review]

**Review by josesanchez1815 — APPROVED** [review]
It appears Ok to me. I randomly went through content and hyperlinks and most of it seems fine content wise.

**Pull request merged**
