### PR TITLE
Add workshop conda material

### LINKED ISSUE #350: Update Conda tutorial based on workshop experience
We can enhance our current conda lesson based on the pilot workshops. 
As @jeremywalter pointed out, the Step 2 in our current conda lesson does not provide enough context and should be rectified. We can add some thing like : `Let’s check our installation to make sure it went smoothly. We can do this by verifying the digital fingerprint or ‘hash’ of the files we just installed.` to this step for clarity.  The updates will be made for the May release.

### PR DESCRIPTION
**Pull request by marisalim**
## PR Checklist

- [x] Release label added
- [x] PR category label added
- [x] PR mergeable
- [x] Clean build logs
- [x] Linked related issues
- [ ] Colorblindness test https://www.toptal.com/designers/colorfilter/ -n/a

## PR Description
adding materials from conda workshop and updating install conda section

**Preview link**
https://cfde-training-and-engagement--355.com.readthedocs.build/en/355/General-Tools/Introduction-to-Conda/
## Review format
comments or direct edits

## Timeline
for may release

### CODE REVIEW

**Comment by jeremywalter** [comment]
image
What is the expected behaviour for this step? For me (Windows OS/Chrome) this opens a binder in a new tab. If this happens on every platform, I think it would be useful to have it say so. (when I do it, it blows up the binder button image which made me not notice the tab opening... so I thought something was wrong).

**Comment by marisalim** [comment]
@jeremywalter - 
we can add a note that the ctrl+ is a suggestion, and OS/web browser dependent i.e., on MacOS/Firefox, when I click the button it doesn't open a new tab

yeah, the zoom feature treats the binder button as an image. since it's a website-wide setting, i'm not sure how to fix the weird gigantic zoom in on the button.

**Comment by jeremywalter** [comment]
@marisalim @s-canchi haha... that zoom in is a 'feature' that Saranya got working forever ago to make our images viewable... can it be disabled on an image by image basis?

**Comment by marisalim** [comment]
i'm not sure - i think @s-canchi looked into this a while ago because it happens with the Snakemake binder button as well.

**Comment by ctb** [comment]
it might be possible to set the CSS class of the button to something different, not sure.

**Comment by s-canchi** [comment]
I haven't finished working on this glitch yet but can plan to look into it for this release as it now impacts two lessons.

**Comment by marisalim** [comment]
if we need a quick fix - we can embed the binder link in text rather than the button image i.e.,

[Launch binder!](https://binder.pangeo.io/v2/gh/nih-cfde/training-rstudio-binder/conda-workshop-march2021?urlpath=rstudio)

instead of 
[Binder](https://binder.pangeo.io/v2/gh/nih-cfde/training-rstudio-binder/conda-workshop-march2021?urlpath=rstudio)

**Review by s-canchi — APPROVED** [review]
lgtm! Love the vidlets and the framing @marisalim 👍

**Pull request merged**
