### PR TITLE
remove plausible analytics script

### PR DESCRIPTION
**Pull request by jeremywalter**
left analytics block for later use

## PR Checklist

- [ ] Release label added
- [ ] PR category label added
- [ ] PR mergeable
- [ ] Clean build logs
- [ ] Linked related issues
- [ ] Colorblindness test https://www.toptal.com/designers/colorfilter/

## PR Description
Briefly describe the changes this PR will add/address
**Preview link**
Add the RTD auto generated preview link

## Review format
Add how you would like to receive the review (direct editing, as comments, notes etc)

## Timeline
Add expected timeline to finish review and merge adding note for time critical updates

### CODE REVIEW

**Comment by jeremywalter** [comment]
This is just a bit of errant code from testing analytics... it will not be used.

**Review by s-canchi — COMMENTED** [review]
Looks good to me. But I am not sure why we are doing this ? Are we replacing it with something else ?

**Comment by jeremywalter** [comment]
> Looks good to me. But I am not sure why we are doing this ? Are we replacing it with something else ?

Plausible was the first analytics service we tested... we will not be using it.

**Review by s-canchi — APPROVED** [review]
lgtm!

**Pull request merged**
