### PR TITLE
intro to GCP tutorial

### PR DESCRIPTION
**Pull request by marisalim**
## PR Checklist

- [x] Release label added
- [x] PR category label added
- [x] PR mergeable
- [x] Clean build logs
- [ ] Linked related issues - n/a
- [ ] Colorblindness test https://www.toptal.com/designers/colorfilter/

## PR Description

introduction to setting up google cloud platform account and instance. uses blast tutorial to demo running an instance, and downloading/uploading files to the instance via google bucket storage.

- [x] add steps/screenshots for authorizing cloud shell - not clear how often this is needed
- [x] add accessing SRA data as a 2nd lesson --> took out config steps
- [x] add costs for examples. blast = ? GCP shows $0...;  sra = $0.04; will put <$1.00
- [x] add button text hightlights 

**Preview link**
https://cfde-training-and-engagement--306.com.readthedocs.build/en/306/Bioinformatics-Skills/Introduction-to-GCP/

## Review format
please comment here and i'll make changes

## Timeline
ideally for Feb 2021 release

### CODE REVIEW

**Comment by abhijna** [comment]
Hi Marisa, 

Nice tutorial. Here are some comments:
- [x] Overall, I think I'm not a huge fan of GCP. I have trouble connecting to the VM each time. It keeps throwing these error messages:
```
abhijna_anand@cloudshell:~ (glossy-observer-301118)$ gcloud compute --project my-first-project-301118 ssh --zone us-west1-b sra
API [compute.googleapis.com] not enabled on project [698918811009].
Would you like to enable and retry (this will take a few minutes)?
(y/N)?  y
Enabling service [compute.googleapis.com] on project [698918811009]...
ERROR: (gcloud.compute.ssh) PERMISSION_DENIED: The caller does not have permission
```

---> the project ID should be `glossy-observer-30118` not `my-first-project-30118`
I tried both. The former gave me an error message.

The same code seems to work sometimes but not at other times.
- [x] Somewhere in the tutorial can you describe the advantages of using  a VM instead of doing all your computation in the cloud shell directly? Like when the terminal says this: `abhijna_anand@cloudshell:~ (glossy-observer-301118)$`

---> it's in the section where we first connect to the cloud shell. the cloud shell doesn't have enough compute power for most bioinformatics/computational analyses
Ok, sorry i missed it. 

- [x] My connection timed out at some point and I had to figure out how to access the VM again. It might be worth adding an admonition telling people that timeouts might happen if they leave their instances on without doing anything for a long time and what to do if it happens.

---> there should be a "Reconnect" button. I added info about the play options
Nice

## First three pages

- [x] Can you make the first bullet point of step one: Visit <https://cloud.google.com/>
- [ ] "After successful sign in, click on "Console" on the top right corner". When I click on the console there was a pop-up window about some acknowledgment that I had to check. I should have taken a screenshot of it but didn't. So maybe look into what that is and include it for first-time users?  

---> i'm not sure what this is. @s-canchi if you see this, please let me know!

- [x] There's a pop-up window after "This is a 2-step process. On the first page, you must agree to the Terms of Service, then click "Continue". On the second page, you'll create your payments profile. Enter your address and billing information, then click "Start free trial". It tells you that you got your free trial. Click "Got it" to close the window.
- [x] Step 3: Check billing account information. Can you point to what you mean by three vertical lines on the image? Probably easiest to put an arrow.
- [x] When I go to billing account, I get this screen: Screen Shot 2021-01-08 at 10 06 41 AM I don't see the "my billing account" button here. But I see it after I click on "Manage billing account"
- [x] Centralized billing account section: did you mean "host organization's" instead of "organization host's" credit card?
- [x] I love the Jon-Janice use case example :) 
- [x] In the setting up a GCP instance page: for this bullet point "Click on "Create Project", enter a unique project name ("My First Project" in the example below), and click "Create". I have two drop-down tabs. One is the "project name" and other is "location". What must I choose for the location?
Screen Shot 2021-01-08 at 10 36 07 AM

- [x] This is the first thing I see when I click on VM instances Screen Shot 2021-01-08 at 12 18 29 PM. Maybe say that the create button is on a pop up window.
- [x] "Names must be in lowercase letters or numbers. Use hyphens "-" instead of spaces. You'll need the VM name to connect to it." This step needs a bit more info. Where am I typing the name? The arrow in the figure does not point to the name tab. It points to zone and rate. Maybe you could move the image to point b.
- [x] Add a note after this sentence that it takes a min for the green checkmark to appear: When you're done configuring the VM, click "Create".
- [x] Open Google Cloud Shell¶. in this section, after this sentence "Click on the "Activate Cloud Shell" icon", tell the user to look at the above image to find where it is on the screen. it might also be useful to put that screenshot below the sentence to make it easier.
- [ ] I didn't get a prompt to set up an ssh public/private key after I entered the verification code. This is my command prompt name: `abhijna_anand@cloudshell:~ (glossy-observer-301118)$`

---> hm, let's document when this occurs/doesn't...

## Blast analysis
- [x] maybe good to add that they need to look at the aws blast tutorial if they want to fully understand what each command does.
- [ ] You installed version 2.9.0 but my version is 
```abhijna_anand@cloudshell:~ (glossy-observer-301118)$ blastp -version
blastp: 2.8.1+
 Package: blast 2.8.1, build Feb 24 2020 01:11:40
```

---> @abhijna  that's odd. i ran it again and got 2.9.0. are you using Ubuntu 20.04? or can you post the install code you used to get this version.
Yeah, it was Ubuntu 20.04 and I pasted the code from the tutorial. 

- [x] After this command `less mm-first.x.zebrafish.txt` remind people that they can use `q` to quit the view.

---> it's in the "Expected Output" tab.
Can you move it to the text in case they're not really interested in looking at the expected output tab? I sometimes don't :D 

- [x] minor point: SDK stands for software development kit. you could drop the word toolkit after to avoid repetition.
- [ ] I saw a bunch of different options under `Step 5: Configure Google toolkit`
 For example:
```
Pick configuration to use:
 [1] Re-initialize this configuration [cloudshell-16545] with new settings
 [2] Create a new configuration
Please enter your numeric choice:  2
Enter configuration name. Names start with a lower case letter and
contain only lower case letters a-z, digits 0-9, and hyphens '-':
```
I didn't see this step after selecting 2 and there was no link after.

```
"Do you want to continue (Y/n)?": enter Y
```
---> let's document when this happens/doesn't. I don't know how to reproduce this.


- [x] Can you show example output when you run this command 
```
gcloud config configurations list  
```
- [x] Step 6: Maybe a little bit more discussion on what a google storage bucket is and why we might need it would be helpful
- [x]  Step 7: for this command (below) tell them to replace the $BUCKET part with the name of their bucked without the `$`
```
gsutil cp mm-first.x.zebrafish.txt $BUCKET
```
---> this command is right. i had an extra `"` in the alias assignment step that might have tripped this up. please try it again!


- [ ] So i made a bucket and ran the command to copy over the file but it doesn't show up in my bucket. Hmm...
Screen Shot 2021-01-11 at 9 17 30 PM

---> not sure the bucket got set up right? need more details to reproduce the issue.

 - [x] "Note that closing the VM does not stop the instance!" This sentence can be an admonition for better effect.

**Comment by abhijna** [comment]
Dang, I stopped+terminated the VM before I did the SRA tutorial. I will get to that soon. Don't feel like starting a new VM right now.

**Comment by marisalim** [comment]
@abhijna SRA part needs a new VM :)

**Comment by abhijna** [comment]
SRA page comments:

- [x] these sentences would be better as bullet points:
```
Second, type C to open the "Cache" tab. An X should be by “enable local file-caching”. If not, type I to select it. Type O to choose the “location of user-repository”. A green and yellow panel will open up. Use the up and down arrows on your keyboard or your mouse to navigate to the empty directory we made in the previous step. When your directory is selected, click “OK”.
```
- [x] In the last sentence above `When your directory is selected, click “OK”.`, Where is this ok button? I see an OK but it's not a button. Please clarify.

---> i'm not sure what to call it :) but if you click it, it does select "OK". i added more details and arrows.

Looks good. The configuration steps might be better as a vidlet because there's a lot going on there. But vidlets are hard to make so whatever you decide is ok with me.

**Comment by marisalim** [comment]
thanks @abhijna!

question about the google bucket step - 
did you run this command `export BUCKET="gs://<your bucket name>""`? that's where you set what `$BUCKET` is. this command, `gsutil cp mm-first.x.zebrafish.txt $BUCKET` should be run as is with `$BUCKET`.

**Comment by abhijna** [comment]
Yes I did! And then the `gsutil cp mm-first.x.zebrafish.txt $BUCKET` command did not run. I didn't save the error message.

**Comment by marisalim** [comment]
thanks for the feedback @abhijna!

for anyone else reviewing this PR, please see the comments I added to:

https://github.com/nih-cfde/training-and-engagement/pull/306#issuecomment-757068516

there are some config, etc. issues that Abhijna found, but I'm unsure how to reproduce. If you come across any of these or others that are not covered in the tutorial, I'd appreciate screenshots/error messages so I can track down solutions!

**Comment by s-canchi** [comment]
@marisalim - Nice tutorial! Kudos on cracking a tough nut :)
Lesson and step wise comments. I have fixed some of these in the PR I opened with edits to the GCP lesson. But adding here for record:

- [x] Recommend renaming the lesson folder to expand the GCP (similar to AWS lesson). So -> **Introduction to Google Cloud Platform**

---> I'm going to keep it shorter so the left TOC is 1 line

### Setting up GCP account

- [x] Mention need to use chrome browser again on top of the lesson. I almost missed it since it buried in prerequisites tab which is not visible on overview page.
- [x] In Step 2: for the second step, mention the account types business vs individual. Do any features change based on account type ?

---> i'm not sure, but i think we can stick to individual account

- [x] Step 3:  Click on horizontal lines not vertical
            - Add snapshot of in-between page 
            - How can one rename their billing account ? Could not find that info anywhere. 
       
 - [x] Separate the billing act info from add members info. Again this makes sense for a business act but would it make sense for an individual acct type ?

### Setting up GCP instance

- [x] Step 1: make a info box about the project quota: the google link to the faq :  https://support.google.com/cloud/answer/6330231

- [x] Add tip/info to refresh the page if project ID doesn't show up. My project didn’t show a project ID in the table. I clicked the three vertical dots in the row of my project to go to Settings which listed the project ID. Using back button from the setting page to go back to the manage resources page was hung up. Refresh of the page fixed it tho.

---> the project ID shows up in the Google cloud shell, so you don't really need to search for it on the manage project page anymore

- [x] Step 2: show arrow for the navigation icon which can be accessed from any page. Also arrow for the Compute heading which I missed the first time.
           - For this step I first got a message saying enable billing. But then I realized I was in the wrong project which can be accessed using the drop down menu on the top header bar. —> This is important to note!
             - **Question** —> Can you have projects within an account to which the default billing doesn’t apply ? That is quite confusing.
             
             ---> don't think so? 

            - In the create instance step I had the page load a while…. Had to reload the page again to reset.
            
            - Could use better placement of text and images. 
        
- [x] Add info box with link to the zones and regions: https://cloud.google.com/compute/docs/regions-zones?_ga=2.51208687.-79235869.1601574422

- [x] Step 2d. - say click “select” for finalize your choice

- [x] Don’t mention the api and identity section- just say leave default 

- [x] Step f should be about all vm creation. Can move the click Crete to step e.

- [x] Confused by the “Reconnect” button in tip box. I don’t see it on the page.

---> it only shows up when the connection is lost

- [x] Step 3:  Couldn’t easily locate the icon for step b. Suggest screenshots for each step
        - In Step d : missing info after clicking authorize and entering Y…. Requesting a paraphrase which is in step e
        - After I click Authorize it went straight to step e on command line….. I tried to do cloud auth login after the prompt was returned but it is said use service accts for authentication. Should I do this step or not ? Yes but could help to have a screenshot 

### Blast Analysis

- [x] Step 2: confused as to where this is setup. Can’t see it as one of the options in the native filesystems. The commands worked however.

---> you have to navigate back a few directories to see /mnt, but it's not necessary to, these commands can be run from the default filesystem

- [ ] Step 5: Why reconfigured again? I selected the first option and ran through the setup without needing to again create a verification link.
- [x] Step 8: Better to link to a small test file that users to can download and follow along. 

### Download SRA data

- [x] Step 1: confused as to why one project cannot have multiple instances ? I create a new instance within the same project. For step 1 it would be useful to just list the instance config options (there are only 3-4).

---> yes, projects can have multiple instances. in terms of billing, GCP tracks it by project. to get cost estimates for each example, i had to run VMs in separate projects

- [x] Maybe just have one screenshot of the instance with all options.


- [x] I found the navigation to be tricky to return the previous page after the last step in the example 1. I found using Recent under navigation to  go back to previous pages useful.

---> the Recent menu only shows up if you allow Google to track your usage on the cloud! 

- [x] Link the connect to instance steps in step 1. 

The remaining comments were about getting the SRA toolkit working which you have already made corrections to the lesson!

**Comment by marisalim** [comment]
thanks @s-canchi! merged in your branch and made the edits above. i need to check on the `gcloud` config steps, i had to run it twice, but not sure why it doesn't always show up.

**Review by abhijna — APPROVED** [review]

**Pull request merged**
