### PR TITLE
Reorganization of images to decentralized folders

### LINKED ISSUE #239: Reorganization of the tutorial resources
Currently we host tutorial images under one centralized folder but host additional tutorial resources such as screencasts, example files, scripts etc within the tutorial folder. With the growing list of associated images, it would be better to reorganize the images into either tutorial specific folders or split them back to the original tutorial folder. The tutorial specific resources will also be unified to remove any ambiguity. This is internal organization and will not impact the website render.

### PR DESCRIPTION
**Pull request by s-canchi**
## PR Checklist

- [x] Release label added
- [x] PR category label added
- [x] PR mergeable
- [x] Clean build logs
- [x] Linked related issues
- [x] Colorblindness test https://www.toptal.com/designers/colorfilter/

## PR Description
This PR addresses the image reorganization from centralized folder to local tutorial specific folders to allow for better tracking. I have completed the porting for CFDE Portal and MIME type tutorials. I also edited the style guide to reflect the current guidelines. 
**Preview link**
https://cfde-training-and-engagement--282.com.readthedocs.build/en/282/
## Review format
comments or direct edit.

## Timeline
Due for December release so preferably by Dec 8th.

### CODE REVIEW

**Comment by s-canchi** [comment]
@marisalim @abhijna @josesanchez1815 -- would you port the images for your tutorials over to local folders ? Let me know if you would prefer I do it instead. Create a PR to this PR to merge your changes in.

**Comment by s-canchi** [comment]
Only KF images are remaining to be shifted over. @abhijna would you want to do it ? Considering you might be busy with the tutorials PR, either me or @marisalim can also take care of it.

**Comment by marisalim** [comment]
i'll do the KF img reorg :)

**Comment by abhijna** [comment]
Ok ok and I'm working on use case PR review. It's the worst :(

**Review by marisalim — APPROVED** [review]
KF image reorg is done! @abhijna there will be a `Kids-First/images-kf` folder when this PR is merged.

there's an "orcid-error.png" file in the images/ folder but I don't think it's being used (`git grep orcid` doesn't turn up anything) - anyone remember it?

i re-organized the images for the cfdebot tutorial on #274, so this image reorg PR should be good to go!

**Comment by s-canchi** [comment]
All images are linked and work. Merging!

**Pull request merged**
