### PR TITLE
Snakemake formatting edits and addition of Resources tab

### PR DESCRIPTION
**Pull request by marisalim**
This PR adds:
- format changes noted in #148 
- some text edits and info about Snakemake rule directives
- tabs for 'Snakemake rule'
- bash cheatsheet text/formatting edits
- moves cheatsheets from Snakemake tutorial to a general Tutorial-Reference-Material folder so they can be linked to other tutorials and now there is a place for other ref materials! had to fix path to conda cheatsheet on the install conda tutorial too.

preview: https://cfde-training-and-engagement--149.com.readthedocs.build/en/149/Bioinformatics-Tutorials/Snakemake/

lowish priority PR, but would like to merge soonish so the Tutorial-Reference-Material folder exists on `latest`.

### CODE REVIEW

**Review by s-canchi — COMMENTED** [review]
The changes looks good. I have a few suggestions:

 1. `Tutorial Reference Material` is a long name for the header tab. Could you replace it with `Cheatsheets` or `Resources` or an alternative with smaller foot print. The header and the title on the home page differ by a `s`. 
2. The landing page on Kids First and General is `Overview` while it is `Home` for the Tutorial reference material and Bioinformatics tutorials tabs. It be better to convert all to `Overview`.

3. Would "Highlights" be a better option instead of "Recap" in the admonition boxes ?
 4. In the snakelike_5.md, could the 4 learning objectives be depicted as checked boxes instead of bullet points ?

**Comment by marisalim** [comment]
@s-canchi thanks! made the changes. opted for 'Key Points' instead of 'recap' following Software Carpentries style. the check boxes don't render on Mkdocs, so leaving as bullet points.

**Comment by s-canchi** [comment]
Have you updated the style guide to include the "Key points" and "Learning Objectives" titles ? I used the same style in the MIME tutorial for consistency.

**Comment by marisalim** [comment]
@s-canchi yup, those sections are in the style guide now. any other changes? otherwise, can you approve? :)

**Review by s-canchi — APPROVED** [review]
lgtm!

**Pull request merged**
