### PR TITLE
snakemake code block edits

### PR DESCRIPTION
**Pull request by marisalim**
taking out command prompts from copy/paste blocks

### CODE REVIEW

**Comment by marisalim** [comment]
@ACharbonneau let me know how these changes look! i also edited the conda install tutorial since i did the same thing with the command prompt formatting. Couldn't figure out how to nicely format the command prompts in the code block AND have the copy to clipboard, so i ditched the `(env) $` and added more text instructions instead!

conda install page: https://cfde-training-and-engagement.readthedocs-hosted.com/en/marisa_snakemake_code/General-Tutorials/install_conda_tutorial/

snakemake tutorial where code blocks start: https://cfde-training-and-engagement.readthedocs-hosted.com/en/marisa_snakemake_code/Bioinformatics-Tutorials/Snakemake_tutorial/snakemake_1/

**Comment by ACharbonneau** [comment]
So, one thing that would be really helpful is if we could have one style of code block to indicate "things you should type/copy" and another to indicate "this is output". I'm not sure what settings we have for the code block bits you're using, but if we could at least have two different colors that would be good. Embedding information into the flow of the tutorial makes is easier to learn and easier to teach.

**Comment by marisalim** [comment]
i'm done trying to hack the admonition blocks for now. here's the preview!

https://cfde-training-and-engagement.readthedocs-hosted.com/en/marisa_snakemake_code/Bioinformatics-Tutorials/Snakemake_tutorial/snakemake_3/

**Comment by abhijna** [comment]
lgtm

**Pull request merged**
