### PR TITLE
Added index page 

### PR DESCRIPTION
**Pull request by abhijna**
We now have a landing page for tutorials. Preview here:
https://cfde-training-and-engagement.readthedocs-hosted.com/en/preview/

Suggestions welcome.

### CODE REVIEW

**Comment by ACharbonneau** [comment]
it's beautiful :)

**Comment by ACharbonneau** [comment]
Could you fix the Kids First one? I think I must have started and then gotten distracted because it has an index page, but it doesn't remotely match the KF content 😬

**Comment by abhijna** [comment]
I fixed KF... there's a "push to cavatica" page that i don't understand. It's clearly under development. Do we want to leave it in?

**Comment by ACharbonneau** [comment]
for now I'd drop it. When I was making this tutorial the infrastructure was actually broken, so I just sort of stopped in the middle 😬

**Comment by abhijna** [comment]
Coolio

**Comment by jeremywalter** [comment]
Two observations: 
1) the web development and github trainings are the same except for Working with protected branches... is this by design?
2) the MkDocs tutorial is literally titled 'MkDocs' --> could be a little more descriptive (the link is) 
Functionality and look -- first class!

**Comment by abhijna** [comment]
1) This is by Amanda's design
2) Good catch, I will change it
3) Thanks 😊

**Comment by abhijna** [comment]
Automagic TOC done. Can someone check all the links carefully. I had to make a lot of changes, so I may have missed something.
@josesanchez1815 @jeremywalter

**Comment by josesanchez1815** [comment]
### I am not sure which links are supposed to be done, but these lead to a Github Repository, I am not sure if that was intentional. I am referring to the links for branch, pull request, and merged.
image


### preview branch and use that link to render on a PR - > This link leads to a really weird page. Some of the icons are super big.
image

### The Fair CookBook also links to a really weird page where the page is zoomed in and all the content looks pretty big.
image

**Comment by jeremywalter** [comment]
> ### I am not sure which links are supposed to be done, but these lead to a Github Repository, I am not sure if that was intentional. I am referring to the links for branch, pull request, and merged.
> image

I got sent to definitions for branch and merged, and a github tutorial section for the PR (so they are fine on my mac using chrome).

**Comment by jeremywalter** [comment]
> ### preview branch and use that link to render on a PR - > This link leads to a really weird page. Some of the icons are super big.

yes, this is broken
> 
> ### The Fair CookBook also links to a really weird page where the page is zoomed in and all the content looks pretty big.
I don't see this at all... am I looking at the right things?

I don't see this at all. Am I looking at the wrong render?

**Comment by marisalim** [comment]
i think the cookbook link is broken, it should go to here: https://cfde-published-documentation.readthedocs-hosted.com/en/preview/the-fair-cookbook/

**Comment by abhijna** [comment]
@jeremywalter try deleting your cache and cookies

**Comment by abhijna** [comment]
the definition links are intentional... mostly because when i first started with GitHub I had no idea what those terms meant and had to keep looking them up.

**Comment by marisalim** [comment]
the link for 'preview branch and use that link to render on a PR.' sends me to a broken page: https://cfde-training.readthedocs.io/en/latest/Tutorials/ProtectedBranch_HowTo/#preview-website-on-github-branch

image

**Comment by abhijna** [comment]
ok i think i fixed that link

**Comment by abhijna** [comment]
@josesanchez1815 how did you get to the documentation website from the training website?

**Comment by marisalim** [comment]
yay - preview branch link works!

**Comment by abhijna** [comment]
> > ### The Fair CookBook also links to a really weird page where the page is zoomed in and all the content looks pretty big.
> 
> I don't see this at all. Am I looking at the wrong render?


I can't find this either. Looks like Jose got to the documentation page somehow.

**Comment by marisalim** [comment]
the fair cookbook broken link is from the preview version of the published-docs website.

**Comment by josesanchez1815** [comment]
https://cfde-training.readthedocs.io/en/latest/General-Tutorials/cfdebot_website_editing/

There is a hyper link at the very bottom called "HERE

**Comment by abhijna** [comment]
Oh I see it... @marisalim that's the bot tutorial you wrote. Where did you mean to link it?

**Comment by marisalim** [comment]
hmm, it works for me. possibly is should just be a static text instead of a link. that part is saying you should go to this link to check the changes in preview website: 'https://cfde-published-documentation.readthedocs-hosted.com/en/preview/'

**Comment by marisalim** [comment]
oh i see. ok so that link in my cfde-bot tutorial works. but once you go there, the faircookbook link on the home page is broken. 

that's actually fine - the preview webpage will be constantly changing, so stuff is not meant to necessarily work if you go the link in my tutorial.

**Comment by ACharbonneau** [comment]
> 1. This is by Amanda's design
> 2. Good catch, I will change it
> 3. Thanks 😊

Re: 1...I'm not sure what I did but it was probably just some dumb hack, feel free to make it something good :)

Re: links to glossary terms: You should like to the rendered glossary, which is still under development, but lives https://cfde-published-documentation.readthedocs-hosted.com/en/latest/spec-and-docs/CFDE-glossary-test/

**Pull request merged**
