### PR TITLE
Connecting to AWS and running BLAST on AWS

### PR DESCRIPTION
**Pull request by josesanchez1815**
Some additions
rearranged the TOC - General Tutorials
reorganized index.md - Alphabetize Headers
added introtoaws.md - tutorial for connecting to AWS via Windows
added missing.png photos that need to be included in the intro to aws tutorial

What to Review: Do you like how I reorganized the order of links in the TOC as well as the index.md in General Tutorials
Do all the images in intro to aws show up nice and neat?
Do all of the images zoom in when you click on them?
Are the tutorials easy to follow?

Where to Find it:
https://cfde-training-and-engagement.readthedocs-hosted.com/en/josesanchez-aws-blast/

How you want it reviewed:
Just check and see if the links work, do the images zoom in when you click on them

This is not a time sensitive issue. Whenever you have a chance!

### CODE REVIEW

**Comment by marisalim** [comment]
(minor formatting note: the markdown right-side TOC follows a linear logic for using the '#', '##', '###', etc. on headers. The blast tutorial 'install blast' step had a single '#', which stopped the auto-TOC from that point onwards on the doc. fixed it by making it a double '##')

**Comment by marisalim** [comment]
@josesanchez1815 
The vidlets look so nice! [Here are my comments for edits](https://hackmd.io/5oGXUMpfTISgAIVx-706oA?view) - i was looking at [this version of the site](https://cfde-training-and-engagement--137.com.readthedocs.build/en/137/)

**Comment by abhijna** [comment]
Hi Jose,

This is very well done! I have a few suggestions... sorry it took me so long to get you these. 

* right now your "intro to AWS" is one giant page. I think it might be better to divide it into smaller pages like Marisa and I did with the bioinformatics tutorials because there is a lot of content. You would have to create a folder called "Intro-to-AWS" and split the content into individual .mds. Let me know if you need help with this and I can assist. Also having smaller pages means that when I (or someone else) makes an AWS tutorial, I could easily direct them to specific AWS pages you made.

* it might be helpful to have these sections on the first page of the aws tutorial: "What is AWS", "Goals", "Prerequisites". you can use admonitions to format them. If you decide to divide up the tutorial into individual .mds, these sections would be on the Overview/Home page.

* right now you have the video as the first thing and then some steps. do you want the user to watch the video first and then read the tutorial? Or is the tutorial describing the same things as the video? Make this clear to the user somewhere (preferably before the video)

* make this link "https://aws.amazon.com" clickable (below video).

* is there a way to make the link in the "Note" admonition clickable? 

* there's a typo on this line: "Check to make sure the location corresponds your location is correct."

* tell them it **is important** to keep the location of the machine the same as yours. When Amanda was working on my GWAS, the locations were different and that changed the computers config. Right now I am in an "Ohio" machine. I don't see this screen:
Screen Shot 2020-08-18 at 11 04 05 AM

* I would add an arrow to where your red circles are (especially if they are in the corners of the screen) so the user doesn't have to spend any time looking for a circle. You have done that in some images.

* at 10 mins and 24 sec into the AWS video, the "Lunch" button that you ask them to push is not visible on your screen.

* ooh your key pair section is awesome. it would be nice to have a page for it - I would like to link my tutorials to that page when I'm talking about the key pairs.

* in the "select the public DNS name for later use" section, what do you mean by "save for later use".. Do you want people to paste it somewhere and save it on their local computer or do you want them to remember that this webpage is where it lives?

* i like that you have an arrow in the "Start a new session" image. Maybe you can make it a little bit smaller for other figures, though :) 

* in the "specify session key" section, where am I putting the "full path". There are three red circles. Is it the last one? Maybe you can put numbers next to the red circles and specify which number you're talking about in the text. 

* move the warning about data loss when you terminate an instance to the top of the section. It can be right below the "Terminal the Instance" subheading. You don't want people to follow directions and then see the warning :'(

* maybe add ( to the "Terminate" section) that if people have downloaded/uploaded things into AWS, they should download whatever they need before terminating.

**Comment by josesanchez1815** [comment]
I will need to remember to edit out the web address throughout the tutorial video. That is probably not something other users should be allowed to see for security purposes.

**Comment by josesanchez1815** [comment]
Currently breaking up my tutorial into multiple pages

**Comment by josesanchez1815** [comment]
Having issues with breaking up the pages...will consult with others tomorrow.

**Comment by ctb** [comment]
> I will need to remember to edit out the web address throughout the tutorial video. That is probably not something other users should be allowed to see for security purposes.

which web address - can you explain? it should be fine if it's something AWS is constructing for you, as no one else will have the security credentials to access it.

**Comment by josesanchez1815** [comment]
AWS has their own tutorial to create an AWS account and they have their
information like the url blurred...so I thought maybe I should do the same.

**Comment by josesanchez1815** [comment]
Notable things to fix for my updated PR.

- Broken Link for my tutorial on the Bioinformatics landing page
https://cfde-training-and-engagement.readthedocs-hosted.com/en/josesanchez-aws-blast/Bioinformatics-Tutorials/

- Need to fix video to include the launch button at 10:24

- Need an explanation for what curl does

**Comment by marisalim** [comment]
landing page link works now :)

**Comment by josesanchez1815** [comment]
Thanks Marisa!

**Comment by josesanchez1815** [comment]
As it appears, I think I need to take a careful check on making sure this follows Marisa's Style Guide.

**Review by marisalim — APPROVED** [review]
lgtm!

**Comment by marisalim** [comment]
reminder: per release plan, this PR needs 1 more reviewer to approve

**Comment by abhijna** [comment]
ok i will look at it. might want to update this branch with changes in dev

**Comment by abhijna** [comment]
I made some minor changes. I'm still working on this, here are my first set of comments:

- [x]  "You may choose to follow the walkthrough tutorial video first or proceed to follow the instructions provided on the webpage". What webpage are you talking about? AWS or the next page of this tutorial? can you link?
- [ ] Just to confirm, the two vidlets (mac vs windows) are the same, right? the mac one has been cut short?
- [ ] this sentence on the `Setting up an AWS instance` page is super confusing:
"There are several optional set up configurations. You can either click "Review and Launch" now to start the instance we've configured thus far in the tutorial without these additional configurations or as necessary, click on the following tabs to continue configuring. "
- [ ] There's a sentence in the "Add Tags" tab. "Learn more about tagging your Amazon EC2 resources". Should this be linked to something?
(the tabs in step 5 are very cool, but I'm not sure how much useful information I got out of it. All the words make sense but I don't know if I could do any of the things describes there if I were following this tutorial.

**Comment by marisalim** [comment]
@abhijna For the sentence below, I was trying to explain that users can do the 1st config step and launch the instance, but there are additional ways to customize the configuration; those are listed in the tabs. I've not really used those other configuration steps, so I don't know how to elaborate. It does look like there should be links on a few of them (add tags, storage options) - @josesanchez1815 do you have links for these?

> "There are several optional set up configurations. You can either click "Review and Launch" now to start the instance we've configured thus far in the tutorial without these additional configurations or as necessary, click on the following tabs to continue configuring. "

**Comment by marisalim** [comment]
the other config steps are on the top of this screenshot:

image

**Comment by marisalim** [comment]
(fyi - the .pages and index file conflicts are because i moved 2 tutorials to CFDE Internal Training. I'll fix them when this PR is ready to merge)

**Comment by abhijna** [comment]
Ok i did a thing to make the website build, but you might have to fix it later anyway.

**Comment by josesanchez1815** [comment]
In regards to these, I didn't include them that much because I didn't focus heavily on those steps. They are not necessary to start an instance as they will resort to default values. I can find links.


@abhijna For the sentence below, I was trying to explain that users can do the 1st config step and launch the instance, but there are additional ways to customize the configuration; those are listed in the tabs. I've not really used those other configuration steps, so I don't know how to elaborate. It does look like there should be links on a few of them (add tags, storage options) - @josesanchez1815 do you have links for these?

"There are several optional set up configurations. You can either click "Review and Launch" now to start the instance we've configured thus far in the tutorial without these additional configurations or as necessary, click on the following tabs to continue configuring. "

**Comment by josesanchez1815** [comment]
> I made some minor changes. I'm still working on this, here are my first set of comments:
> 
> * [x]   "You may choose to follow the walkthrough tutorial video first or proceed to follow the instructions provided on the webpage". What webpage are you talking about? AWS or the next page of this tutorial? can you link?
> * [ ]  Just to confirm, the two vidlets (mac vs windows) are the same, right? the mac one has been cut short?
> * [ ]  this sentence on the `Setting up an AWS instance` page is super confusing:
>   "There are several optional set up configurations. You can either click "Review and Launch" now to start the instance we've configured thus far in the tutorial without these additional configurations or as necessary, click on the following tabs to continue configuring. "
> * [ ]  There's a sentence in the "Add Tags" tab. "Learn more about tagging your Amazon EC2 resources". Should this be linked to something?
>   (the tabs in step 5 are very cool, but I'm not sure how much useful information I got out of it. All the words make sense but I don't know if I could do any of the things describes there if I were following this tutorial.

The mac and the windows vidlets are slightly different. At the beginning they are similar, but they differ towards the end when talking about how to connect to an instance(Mobaxterm or Mac Ssh)

**Comment by marisalim** [comment]
@abhijna did the AWS tutorial go away? i don't see it under general

**Comment by abhijna** [comment]
argh, no but it got taken out of the index page because of Saranya's reorg. I think it might be back now.

**Comment by s-canchi** [comment]
I didn't find it in the .pages and index so I added it in. Just your friendly PR passerby :)

**Comment by abhijna** [comment]
Ok I added some links. There may be a few more things to fix/clarify for the December release, but it looks fine for now.

**Pull request merged**
