### PR TITLE
RNAseq on Cavatica tutorial

### LINKED ISSUE #317: Tutorials to run RNAseq on Cavatica
Create user friendly tutorials to run RNAseq on Cavatica. It should use data from KF and be completely all on the platform.

### PR DESCRIPTION
**Pull request by s-canchi**
## PR Checklist

- [x] Release label added
- [x] PR category label added
- [x] PR mergeable
- [x] Clean build logs
- [x] Linked related issues
- [x] Colorblindness test https://www.toptal.com/designers/colorfilter/

## PR Description
This PR adds the RNAseq on Cavatica tutorial along with:
- added the tutorial to Bioinformatics index
- made some styling changes for the tutorial
- added some extra pymarkdown extensions

**Preview link**
https://cfde-training-and-engagement--316.com.readthedocs.build/en/316/Bioinformatics-Skills/RNAseq-on-Cavatica/rna_seq_1/

## Review format
In comments and I will edit the lessons myself.

## Timeline
Expect merge for Feb release

### CODE REVIEW

**Comment by marisalim** [comment]
@s-canchi 

Great tutorial! This will be good material for KF/Cavatica workshops. I reviewed the tutorial on Firefox with KF/Cavatica accounts that are NOT linked to eRA Commons ID.

A few general comments -
- The vidlets are very helpful! I'd switch the order of appearance and add a note at the beginning of the lesson(s) that we recommend watching vidlets first, then following written instructions. I missed some steps when I started with the written instructions.
- For tag, file, and excel column names, tell ppl to use the same names as in the tutorial to avoid naming issues in the app inputs and running R script sections.

I have a lot of specific notes & suggestions per page here --> https://hackmd.io/qR9-1yA2QNKv71kXLxPZHw?edit

**Comment by s-canchi** [comment]
Thanks @marisalim for all the comments and suggestions! Glad to know it worked in an non eRA account :)

**Comment by jeremywalter** [comment]
I did something 'neat'. After completing the filtering and cohort selection I left the page and did some editing. When I came back the 'Open project in Cavatica' button was gone, so I pushed 'Analyze on Cavatica' again and followed the copy authorization protocol for the already selected project. The 'Open project in Cavatica' came back and I clicked it. Now Cavatica has created a project with two copies of every file. I don't know how to fix it so I'll make a new project.

**Comment by jeremywalter** [comment]
I have added several more edits, but am not where I thought I would be (finished!). I'd like to take a closer look at the words in the DESeq2 section and I didn't get through the Data Crunch section yet. Also, some of the data from the DESeq2 portion has changed (in my PCA graph in the HTML the axes are flipped). Otherwise, have successfully completed through Analysis with DESeq2 Public App! :)

**Review by jeremywalter — APPROVED** [review]

**Comment by jeremywalter** [comment]
I have gone through this a few times now and successfully completed all sections but 3b of the data cruncher. I ran the installation chunk successfully but the pcaExplorere code would not run as it does in the video, instead giving me this output:
image

**Review by marisalim — APPROVED** [review]

**Comment by s-canchi** [comment]
Thank you @marisalim @jeremywalter !! This is getting merged in :)

**Pull request merged**
