### PR TITLE
Feb 2021 Release!!

### PR DESCRIPTION
**Pull request by marisalim**
## PR Checklist

- [ ] Release label added
- [ ] PR category label added
- [ ] PR mergeable
- [ ] Clean build logs
- [ ] Linked related issues
- [ ] Colorblindness test https://www.toptal.com/designers/colorfilter/

## PR Description
Briefly describe the changes this PR will add/address
**Preview link**
https://cfde-training-and-engagement--342.com.readthedocs.build/en/342/

## Review format
Add how you would like to receive the review (direct editing, as comments, notes etc)

## Timeline
Add expected timeline to finish review and merge adding note for time critical updates

### CODE REVIEW

**Review by s-canchi — APPROVED** [review]
Yay! lgtm!

**Review by abhijna — APPROVED** [review]

**Comment by abhijna** [comment]
lgtm

**Comment by josesanchez1815** [comment]
Wow the website pages look very nice! Good job guys!

**Review by josesanchez1815 — APPROVED** [review]
I like the new designs put into the Intro to GCP tutorial and the new add ins for the AWS tutorial. Very nice! LGTM

**Review by jeremywalter — APPROVED** [review]
Shiny and wonderful!

**Pull request merged**
