### PR TITLE
cfdebot tutorial - add landing pg info, update PR steps

### PR DESCRIPTION
**Pull request by marisalim**
## PR Checklist

- [x] Release label added
- [x] PR category label added
- [x] PR mergeable
- [x] Clean build logs
- [x] Linked related issues - didn't make an issue for this
- [x] Colorblindness test https://www.toptal.com/designers/colorfilter/ - n/a

## PR Description

I updated the cfde-bot tutorial according to style guide and current PR processes. it is currently written for the CFDE websites that have a single stage PR process going from individual branch to `master` for the public-facing website. i've added a note about the difference from the training website PR process. the training website process could be added once the release plan steps are finalized.

preview: https://cfde-training-and-engagement--205.com.readthedocs.build/en/205/General-Tutorials/cfdebot_website_editing/

## Review format

comments/direct edits

## Timeline

for Oct 2020 release

## Reviewer Checklist

- [ ] spelling and grammar
- [ ] successful run of all installation and code chunks
- [ ] sufficient explanation and details for the tutorial content
- [ ] code syntax and naming convention
- [ ] adherence of tutorial format to style guide
- [ ] functional links (inter and intra)
- [ ] accessible hyperlink text

### CODE REVIEW

**Comment by abhijna** [comment]
The formatting looks good. Here are my comments:
- [x]  typo in this sentence: `The cfde-bots handle changes in each website GitHub repo to check edits and most importantly, prevents changes that could break the website`. I think it should be "prevent".
- [x] are we still calling it the master branch? or should it be "stable" now? or are they interchangeable? 
- [x] "If working from Github, type a new branch name (e.g., my_branch) and hit ENTER. The new branch should be created with the master branch as its base". Where am I typing the branch name??
- [x] Typo in this line: the PR page **will the progress** as the bot goes through its checks, starting with a yellow circle and "Some checks haven't completed yet"
- [x] Can you take out the period from Step 7 and Step 8 titles? for consistency
- [x] Shouldn't this be a hyperlink? https://cfde-published-documentation.readthedocs-hosted.com/en/preview

**Comment by marisalim** [comment]
thanks @abhijna! will make those edits, just a few clarifications:

- I checked the other repos we commonly work on, and they still use `master` and `preview` branches. I *think* this training repo is the only one that has `stable` and `dev`.
- ah i used to have a picture for the branch names. I'll add it back
- I think the last time I had the RTDs link as a hyperlink, it made the html proofer unhappy.

**Comment by ACharbonneau** [comment]
I should make all the others have stable and dev. Its on my list, just haven't done it. Can someone yell at me on Wednesday to do it if I haven't yet?

**Comment by marisalim** [comment]
@ACharbonneau when you add `stable` and `dev` branches to the other repos, does that mean they will also have a 2-step (your branch -> `dev`, `dev` -> `stable`) PR process for pushing changes? 

this cfdebot tutorial was specifically about the steps for pushing changes from our branch -> `master`, which would now change to our branch -> `stable`... do i need to add an intermediate `dev` step?

**Comment by ACharbonneau** [comment]
uhm. I am not really going to do branch fixes today, because I need to get on this report thing for tomorrow. But, please bug me about it later in the week. I think i have to actually look to see what we have to answer your question

**Comment by marisalim** [comment]
- [x] to do: there are some format updates (e.g., keys) that need to be updated before this PR gets merged

**Comment by marisalim** [comment]
@abhijna i'm done fiddling with this tutorial. let me know if it's good to merge. :)

**Review by abhijna — APPROVED** [review]

**Pull request merged**
