### PR TITLE
Training history and overview

### PR DESCRIPTION
**Pull request by raynamharris**
## PR Checklist

- [x] Release label added
- [x] PR category label added
- [x] PR mergeable
- [x] Clean build logs
- [x] Linked related issues #520 
- [ ] Colorblindness test https://www.toptal.com/designers/colorfilter/

## PR Description

- This PR adds a new "workshop history" page that is written in markdown. 
- The html code that previously displayed the workshop history has been deleted from the home page. 
- An overview of the tutorials provided is added to the home page

**Preview link**

https://cfde-training-and-engagement--521.com.readthedocs.build/en/521/?next=https%3A%2F%2Fcfde-training-and-engagement--521.com.readthedocs.build%2Fen%2F521%2F&ticket=ST-1646184655-fFBatnJ8drMvGjfpvDMoyLrrgyRonUB3

## Review format

comments, edits, welcome

## Timeline

within 2 month

### CODE REVIEW

**Comment by raynamharris** [comment]
ready for review

**Comment by ACharbonneau** [comment]
the training link at the bottom appears to be broken: 
image

**Comment by ACharbonneau** [comment]
i think it would be good if the portal demo and hmp thing from the hackathon had the video links as well

**Comment by ACharbonneau** [comment]
This is a very weird sentence: 

>  the CFDE has been hosting free, virtual free, virtual training events covering general and advanced topics in bioinformatics.

**Comment by ACharbonneau** [comment]
clicking on the workshop history link here:
image

forces the link to open in a new tab. can we not do that? I think it's a setting from when we were sending them to the other website

**Comment by ACharbonneau** [comment]
the numbering feels weird to me since they are in reverse chronological order. I like the order tho. Could we move the date to the front and lose the numbering? I think that would make it make more sense

**Comment by ACharbonneau** [comment]
Since you have color coding in the plot, maybe it would be cool to have color-coded list dots in front of the dates? so you could tell at a glance which ones were which.

**Comment by ACharbonneau** [comment]
In the plot:

image

I don't think these numbers are right. I didn't have workshops with zero attendees. 

image


the numbers are not on the right

**Comment by ACharbonneau** [comment]
the names don't always match between the plot and the list:
image

image

**Comment by ACharbonneau** [comment]
This is the same lesson, but keeps changing names
image

**Comment by raynamharris** [comment]
Excellent points. Will correct those things.

**Comment by raynamharris** [comment]
hyperlink removed from figure. and workshops with 0 attendance (in the future) removed

**Comment by raynamharris** [comment]
made names more consistent, changed list to bullets, fixed opening paragraph

**Comment by ACharbonneau** [comment]
> hyperlink removed from figure. and workshops with 0 attendance (in the future) removed

OH IT WAS THE FUTURE! I was never going to guess that. lulz

**Review by ACharbonneau — APPROVED** [review]

**Pull request merged**
