### PR TITLE
Updates to KF portal tutorials: screenshots and text

### LINKED ISSUE #292: Updates to KF tutorial based on latest Portal UI
This issues is a reminder to update the KF tutorials with the latest changes to portal UI. It also provides fixes to some of the errors in the current tutorial which is the basis for the KF pilot workshop on Dec 17th. 

- The first exercise is subsetting to participants based on age. How can you achieve this using the plots ?
On the plots you can only select one bar newborns or [1,5] but not both
https://training.nih-cfde.org/en/latest/Bioinformatics-Skills/Kids-First/Exploring-Data-in-the-KF-Portal/KF_6_Filtering/

- in the second filter lesson, the image of the query shows hispanic filter but it is not mentioned in the text of the lesson
https://training.nih-cfde.org/en/latest/Bioinformatics-Skills/Kids-First/Exploring-Data-in-the-KF-Portal/KF_7_Plots/

- In this exercise, is the age referring to the age at diagnosis or age at outcome ?
https://training.nih-cfde.org/en/latest/Bioinformatics-Skills/Kids-First/Advanced-KF-Portal-Queries/KF_9_AdvancedQuery/

- So if we use the filters in the tab to do the exercises it matches the images in the lessons. But if you use the plots,
      - you cannot select two barplots at the same time so cannot get 0-5 age group
      - the 1-5 age grp shows up as 364-1824 and not 1826.25 like in the images

- So the table view in our screenshots on the explore tab shows columns not currently present in table view: https://training.nih-cfde.org/en/latest/Bioinformatics-Skills/Kids-First/Advanced-KF-Portal-Queries/KF_12_CheckingQueries/
For example the age at diagnosis is not of the column headers, but it is referenced in the lesson to identify participant who occurs in both the queries

### PR DESCRIPTION
**Pull request by s-canchi**
## PR Checklist

- [x] Release label added
- [x] PR category label added
- [x] PR mergeable
- [x] Clean build logs
- [x] Linked related issues
- [x] Colorblindness test https://www.toptal.com/designers/colorfilter/

## PR Description
Updated to screenshots and minor text additions to reflect the latest numbers and look of KF DRC Portal. 
**Preview link**
https://cfde-training-and-engagement--291.com.readthedocs.build/en/291/

## Review format
comments and/or direct edits

## Timeline
merge for Dec2020 release

### CODE REVIEW

**Comment by s-canchi** [comment]
- [x] I will be fixing the screenshots in Joint Queries and Checking Queries by end of 15th.

**Review by abhijna — APPROVED** [review]

**Comment by abhijna** [comment]
@s-canchi in your new screenshots all the arrows are purple vs. the red in all my screenshots. But I'm sure it's not a big deal, but letting you know since you like consistency :D

**Comment by marisalim** [comment]
This PR looks good to me, but let's leave it open for another day in case there are more updates after the workshop :)

**Comment by s-canchi** [comment]
Thank you @abhijna ! I didn't notice the shade difference but was trying to match the KF portal colors. We can update for the next iteration 👍 

@marisalim - I agree and will have it open till tomorrow for any final changes or edits we would like to include.

**Review by marisalim — APPROVED** [review]
good to go!

**Pull request merged**
