### PR TITLE
Automated reviewer assignment and release drafter features

### PR DESCRIPTION
**Pull request by s-canchi**
## PR type

- [ ] New tutorial
- [ ] Fixes to tutorials only on latest
- [ ] Fixes to tutorials on stable and latest
- [x] Feature enhancement
- [ ] Tutorial formatting
- [ ] Website formatting
- [ ] Other

## PR Checklist

- [ ] Release label added
- [x] Milestone added
- [x] PR mergeable
- [x] Clean build logs

## PR Description
This PR will add feature for automated reviewer assignment. It is set up for assigning two reviewers for merge into `latest` and the entire team for merge into `stable`. Another feature will be the automated tracking of PRs for release notes that will be due for every release. The PR template is also modified to reflect these updates. 

## Review description
The functionality has been checked in independent repo and not all can be tested prior to merge. The reviewer assignment function has been tested, confirmed by some of the team members and was used for this PR. 

## Review format
Comments on GitHub or independent notes.

### CODE REVIEW

**Review by marisalim — APPROVED** [review]

**Review by josesanchez1815 — APPROVED** [review]
LGTM

**Comment by ACharbonneau** [comment]
Looks like I wasn't fast enough :) 

I think this automated reviewer assignment thing is worth trying, but I'd like to revisit it later and make sure it's working for people. For example, on this specific PR, I don't think Marisa or Jose know how actions work, so really, I should have been assigned as reviewer so that the reviewer could actually check the PR rather than just assuming it was fine and merging it. I'm a little concerned that this could be an ongoing thing...that people will be assigned randomly to PRs that they aren't necessarily interested in or have the background to access. It's also worth noting that the way it's currently set up, @josesanchez1815  and @jeremywalter are going to get more of the PR review burden than @abhijna, @marisalim and @s-canchi, which is almost certainly opposite of what we want for reviewing bioinformatics content.

**Comment by s-canchi** [comment]
I agree with some of the points made by @ACharbonneau. For PRs with content that match a team member's expertise or experience, it wouldn't hurt to add them manually as an additional reviewer or request them to have a read and provide comments. It is important to note that although we have the automated reviewer setup, the current underlying GitHub setup requires only one approving reviewer for merge into `latest`. The split of the team for reviewer assignment is by design to ensure people with two different sets of background are able to run through the tutorial and provide assessments. This design also assumes that majority of the bioinformatics tutorials would be authored by one of the postdocs. The setup can be adjusted to have the team with same probability of assignment but that doesn't help for review of technical tutorials either. 

We can give this feature a try, take notes on our thoughts and revisit it a later time to discuss if it is worth having or are we better without it.

**Comment by josesanchez1815** [comment]
I'm ok with trying the feature and if I ever get something I am unsure about. I think I would just ask questions to the PR Requester or get some help from the rest of you to make sure I understand what is going on. So, this is my bad for not asking questions. (I do not know how actions work)

**Pull request merged**
