### PR TITLE
Fixing .pages tutorial titles + homepage revision

### PR DESCRIPTION
**Pull request by marisalim**
## PR Checklist

- [x] Release label added
- [x] PR category label added
- [x] PR mergeable
- [x] Clean build logs
- [x] Linked related issues - n/a
- [x] Colorblindness test https://www.toptal.com/designers/colorfilter/ - n/a

## PR Description

Some of the tutorial titles in the .pages files were different than the landing page - edited on web devo, bioinf skills, and cheat sheets. New version of the home page!

**Preview link:** https://cfde-training-and-engagement--243.com.readthedocs.build/en/243/?next=https%3A%2F%2Fcfde-training-and-engagement--243.com.readthedocs.build%2Fen%2F243%2F&ticket=ST-1602560267-WNIHEemR23jD1s93P3822kMOkC56Na1Y

## Review format

comment in PR if there are other inconsistent titles

## Timeline

before Thursday, preferably today :)

### CODE REVIEW

**Comment by marisalim** [comment]
@jeremywalter - edited the overview/TOC titles. let me know if more need edits!

**Comment by jeremywalter** [comment]
CFDECloud

**Comment by marisalim** [comment]
@s-canchi i changed the javascript title to be broader (Javascript Tutorials).. because the left TOC already has the Enabling user choice title and we may be adding more Javascript tutorials in the future

**Comment by s-canchi** [comment]
I found the original title too broad and confusing. Even with the possibility of adding more javascript tutorials in the future, this tutorial may still remain a folder on its own holding all its tutorial materials. In that scenario this might become a nested folder within the broader Javascript folder level.

**Comment by jeremywalter** [comment]
--working draft-- comments and edits welcome --> note we need a contact tag on this site until we decide/set-up jira

## Welcome to the CFDE Training Resource Center!

Our mission as the Common Fund Data Ecosystem (CFDE) Coordinating Center is to make Common Fund (CF) data accessible to researchers like you. Choose from our growing list of tutorials and resources to learn how to access data and perform bioinformatic analyses. 

For the novice, we recommend starting with tutorials on computing environment setup [link to Conda, AWS], while experienced users may find our tutorial on snakemake workflow management [link to snakemake] helpful. 

Learn to build cohorts across multiple CF datasets using the CFDE Portal [link to tutorial] or in the Kids First data portal, a CF program [ link to KF tutorials]. 

image


Check the release notes [link to release notes] for our latest tutorial updates. If you have comments or suggestions, please [contact us](mailto:coordination@CFDE.groups.io)!

**Comment by marisalim** [comment]
@jeremywalter  there is an email link at the bottom of the website that goes to the auto helpdesk email. maybe link to the email in the "please contact us" text?

**Comment by s-canchi** [comment]
I think it is interesting that we have not defined CFDE anywhere in the homepage but it is the largest word that jumps out from the word cloud.

**Comment by ACharbonneau** [comment]
> I think it is interesting that we have not defined CFDE anywhere in the homepage but it is the largest word that jumps out from the word cloud.

the title of the page is "Welcome to Common Fund Data Ecosystem Training Resources" ?

**Review by s-canchi — APPROVED** [review]
lgtm! Checked all the links and spellings as well :)

**Review by jeremywalter — APPROVED** [review]
I forced Marisa to change the javascript title back... I agree this may need to change in a future iteration, but for this one there is only the one tutorial and it's cryptic to have a dropdown that just goes to one tutorial... it's also totally out of sync with all the other links that go straight to the tutorial... when we get bigger we will probably need a way to make dropdown menus (I suspect). Good work with all the words and colors and links! :P

**Pull request merged**
