### PR TITLE
Addition of landing page info for Sphinx and Javascript tutorials: website style guide

### LINKED ISSUE #224: Add landing pg info for sphinx web dev tutorial
The General Tutorials need landing page information (added to top, not separate page). It would be great to get these updated for the Oct 2020 release so they all have, at minimum, the learning objective(s), prerequisites, and estimated time to complete sections. As applicable, include a tutorial resources tab (e.g., to link github repos for the website rendering tutorials). See style guide and/or the conda install tutorial for ref. 

This issue is for: Sphinx for static websites editing

### LINKED ISSUE #226: Add landing pg info for Javascript tutorial
The General Tutorials need landing page information (added to top, not separate page). It would be great to get these updated for the Oct 2020 release so they all have, at minimum, the learning objective(s), prerequisites, and estimated time to complete sections. As applicable, include a tutorial resources tab (e.g., to link github repos for the website rendering tutorials). See style guide and/or the conda install tutorial for ref. 

This issue is for: Adding user choosable content using Javascript

### PR DESCRIPTION
**Pull request by marisalim**
## PR Checklist

- [x] Release label added
- [x] PR category label added
- [x] PR mergeable
- [x] Clean build logs
- [x] Linked related issues
- [x] Colorblindness test https://www.toptal.com/designers/colorfilter/ - n/a

## PR Description

adding landing pg info for Sphinx and Javascript tutorials. I also made the Javascript tutorial its own folder within General, so the demo script (script and rendered versions) are in there.

preview: https://cfde-training-and-engagement--230.com.readthedocs.build/en/230/General-Tutorials/

## Review format

in the comments

## Timeline

for oct 2020 release

## Reviewer Checklist

- [x] spelling and grammar
- [ ] successful run of all installation and code chunks
- [x] sufficient explanation and details for the tutorial content
- [x] code syntax and naming convention
- [x] adherence of tutorial format to style guide
- [x] functional links (inter and intra)
- [x] accessible hyperlink text

### CODE REVIEW

**Review by s-canchi — COMMENTED** [review]
Looking good @marisalim. Here are my suggestions:
Sphinx tutorial: https://cfde-training-and-engagement--230.com.readthedocs.build/en/230/General-Tutorials/Sphinx_Tutorial/
- [x] Title in the left TOC and on the page do not match
- Prerequisites 
    - [x] lists GitHub account, but apart from cloning the demo repo (for which you do not need a GitHub account) it is not used again. May be say access to git instead ?
     - [x] list Python or Conda as a requirement 
- Tutorial Resources 
     - [x] Bullet point not needed
- Installation Instructions
     - Both pip and Conda can work on both MacOS and Windows. Right now it is shown as Conda for MacOS and pip for Windows. Reorg to show package manager instead. **-> the Sphinx page lists conda for MacOS and pip for Windows. pending need, I'm leaving it with conda and pip**
     - [x] Replace `this tutorial` in "Based on this tutorial." with `official Sphinx installation guide`.
     - [x] Replace `here` in "We will utilize conda package management system to install Sphinx. If you do not have conda installed, you can follow installation steps here." with instructions for Windows or MacOS. Can link the install conda tutorial for MacOS.
     - [x] Replace `here` in "If Python is not installed, you can download from here." with `official Python website` 
     - [x] Replace `Sphinx` link in "To install Sphinx, we will use pip which is a python package installer." with https://www.sphinx-doc.org/en/master/usage/installation.html
- Body
     - [x] Maybe add Step # to titles ?
     - Add key points admonition at the end **-> do you have suggestions? otherwise, we made Key Points optional, especially on shorter tutorials.**

Javascript tutorial: https://cfde-training-and-engagement--230.com.readthedocs.build/en/230/General-Tutorials/Javascript-chooser/javascript_chooser/
- [x] Title in the left TOC and on the page do not match
- [x] Est. time can say 30 mins without about to keep it consistent
- Can the demo javascript and rendered file be moved to resources ? The smaller title of the folder name in the left TOC looks odd. **--> for now, all the tutorial-specific resources are being kept with the tutorial. that is pending a broader re-org decision**
- If there is a way to link the steps in the body to the steps in the overview ie make them clickable, that would be neat. **--> probably, but the right TOC does that**

**Comment by marisalim** [comment]
@s-canchi edits done, see edited comment above!

**Comment by s-canchi** [comment]
This is what I have for Key Points for MkDocs: 

> You now have a workflow to customize your static website, generate content and host on [readthedocs.com](https://readthedocs.com/). Enjoy your new website!

You can include something similar or you can choose to not include it :)

**Comment by s-canchi** [comment]
One final suggestion would be to change the Javascript folder name from `Javascript chooser` to `Javascript dropdown box`. What do you think ?
Otherwise LGTM!

**Review by s-canchi — APPROVED** [review]

**Pull request merged**
