### PR TITLE
update paths AWS

### PR DESCRIPTION
**Pull request by raynamharris**
## PR Description

* renames main folder from "Introduction_to_Amanzon_Web_Services" to "Introduction-to-AWS"
* renames "introtoaws1.md" to  "index.md"
* renames all other "introtoaws*.md" files to "aws*.md"
* updates other links pointing to aws lesson

 ## PR Checklist

- [x] Release label added
- [x] PR category label added
- [x] PR mergeable
- [x] Clean build logs
- [x] Linked related issues #532 
- [ ] Colorblindness test https://www.toptal.com/designers/colorfilter/

**Preview link**
https://cfde-training-and-engagement--534.com.readthedocs.build/en/534/

### CODE REVIEW

**Comment by abhijna** [comment]
Hi @raynamharris, It seems I don't have access to the readthedocs anymore. Without a preview, I can't really review this PR for broken links (which would be my only concern with renaming files). Do you have any suggestions on how to review it?

**Comment by raynamharris** [comment]
ah, that makes sense. I will ask @jeremywalter to reactive your read the docs access tomorrow. thanks!

**Review by jeremywalter — COMMENTED** [review]
I don't see the aws5.md (through the link or in the repo).

**Comment by ctb** [comment]
@abhijna do we need this to be merged for the JOSE paper / do I need to add any comments on the JOSE paper review?

**Comment by raynamharris** [comment]
@jeremywalter there are only 4 lessons so there shouldn't be an aws5.md file. previously, there was a whole page devoted to a video tutorial but i incorporated that into the index and linked it appropriately. is there a pointer to aws5.md still?

**Review by jeremywalter — APPROVED** [review]
Giving this conditional approval... I tried to fix a link that wasn't working right to the videos on the Setting up an AWS Instance page. I failed so I replaced it with text. Everything else looks good, links checked.

**Review by abhijna — APPROVED** [review]
All the links I care about work! Thanks, Jeremy and Rayna. This PR doesn't need to be merged in for AWS Jose paper but doesn't hurt :)

**Pull request merged**
